In [1]:
import imutils
import argparse
from imutils.video import VideoStream
from imutils.video import FPS
import numpy as np
import time
import cv2
import os
import import_ipynb
from pyimagesearch import CentroidTracker
from pyimagesearch import TrackableObject
import dlib


importing Jupyter notebook from pyimagesearch.ipynb


In [2]:
prototxt = os.path.join("mobilenet_ssd/MobileNetSSD_deploy.prototxt.txt")
model = os.path.join("mobilenet_ssd/MobileNetSSD_deploy.caffemodel")
input_file = os.path.join("videos/example_01.mp4")
# input_file=""
output_file = os.path.join("output/final.mp4")
skip_frames = 30
min_confidence = 0.4

In [3]:
CLASSES = ["background", "aeroplane", "bicycle", "bird", "boat",
    "bottle", "bus", "car", "cat", "chair", "cow", "diningtable",
    "dog", "horse", "motorbike", "person", "pottedplant", "sheep",
    "sofa", "train", "tvmonitor"]

# load our serialized model from disk
print("[INFO] loading model...")
net = cv2.dnn.readNetFromCaffe(prototxt,model)


[INFO] loading model...


In [4]:
print(len(str(input_file)))
if len(str(input_file))==0:
    print("[INFO] starting video stream...")
    vs = cv2.VideoCapture(0)
    time.sleep(2.0)
# otherwise, grab a reference to the video file
else:
    print("[INFO] opening video file...")
    vs = cv2.VideoCapture(input_file)

21
[INFO] opening video file...


In [5]:
# initialize the video writer (we'll instantiate later if need be)
writer = None

# initialize the frame dimensions (we'll set them as soon as we read the first frame from the video)
W = None
H = None

# instantiate our centroid tracker, then initialize a list to store
# each of our dlib correlation trackers, followed by a dictionary to
# map each unique object ID to a TrackableObject
ct = CentroidTracker(maxDisappeared=40)# maxDistance=50
trackers = []
trackableObjects = {}

# initialize the total number of frames processed thus far, along
# with the total number of objects that have moved either up or down
totalFrames = 0
totalDown = 0
totalUp = 0

# start the frames per second throughput estimator
fps = FPS().start()

In [6]:
while True:
    # grab the next frame and handle if we are reading from either VideoCapture or VideoStream
    frame = vs.read()
    frame = frame[1] if (input_file, False) else frame
    print(frame)
    #print(frame,type(frame))

    # if we are viewing a video and we did not grab a frame then we have reached the end of the video
    if input_file!="" and frame is None:
        break

    #frame=np.array(frame,dtype=object)

    # print("\n\n")
    #print(frame)
    #print(frame[1].shape)
    #print(frame.dtype)
    # resize the frame to have a maximum width of 500 pixels (the
    # less data we have, the faster we can process it), then convert
    # the frame from BGR to RGB for dlib
    
    frame = imutils.resize(frame, width=500)
    #frame = imutils.resize(frame[1], width=500)
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    

    # if the frame dimensions are empty, set them
    if W is None or H is None:
        (H, W) = frame.shape[:2]

    # if we are supposed to be writing a video to disk, initialize the writer
    if output_file!="" and writer is None:
        fourcc = cv2.VideoWriter_fourcc(*"MJPG")
        writer = cv2.VideoWriter(output_file, fourcc, 30, (W, H), True)
    
    # initialize the current status along with our list of bounding
    # box rectangles returned by either (1) our object detector or
    # (2) the correlation trackers
    status = "Waiting"
    rects = []

    # check to see if we should run a more computationally expensive object detection method to aid our tracker
    if totalFrames % skip_frames == 0:
        # set the status and initialize our new set of object trackers
        status = "Detecting"
        trackers = []

        # convert the frame to a blob and pass the blob through the network and obtain the detections
        blob = cv2.dnn.blobFromImage(frame, 0.007843, (W, H), 127.5)
        net.setInput(blob)
        detections = net.forward()
        print(f"the detection is {detections} !!!")
        
        # loop over the detections
        for i in np.arange(0, detections.shape[2]):

            # extract the confidence (i.e., probability) associated with the prediction
            confidence = detections[0, 0, i, 2]

            # filter out weak detections by requiring a minimum confidence
            if confidence > min_confidence:

                # extract the index of the class label from the detections list
                idx = int(detections[0, 0, i, 1])

                # if the class label is not a person, ignore it
                if CLASSES[idx] != "person":
                    continue

                # compute the (x, y)-coordinates of the bounding box for the object
                box = detections[0, 0, i, 3:7] * np.array([W, H, W, H])
                (startX, startY, endX, endY) = box.astype("int")

                # construct a dlib rectangle object from the bounding box coordinates and then start the dlib correlation tracker
                tracker = dlib.correlation_tracker()
                rect = dlib.rectangle(startX, startY, endX, endY)
                tracker.start_track(rgb, rect)

                # add the tracker to our list of trackers so we can utilize it during skip frames
                trackers.append(tracker)
    
    # otherwise, we should utilize our object *trackers* rather than object *detectors* to obtain a higher frame processing throughput
    else:

        # loop over the trackers
        for tracker in trackers:

            # set the status of our system to be 'tracking' rather than 'waiting' or 'detecting'
            status = "Tracking"

            # update the tracker and grab the updated position
            tracker.update(rgb)
            pos = tracker.get_position()

            # unpack the position object
            startX = int(pos.left())
            startY = int(pos.top())
            endX = int(pos.right())
            endY = int(pos.bottom())

            # add the bounding box coordinates to the rectangles list
            rects.append((startX, startY, endX, endY))
            
    # draw a horizontal line in the center of the frame -- once an
    # object crosses this line we will determine whether they were
    # moving 'up' or 'down'
    cv2.line(frame, (0, H // 2), (W, H // 2), (0, 255, 255), 1)

    # use the centroid tracker to associate the (1) old object
    # centroids with (2) the newly computed object centroids
    objects = ct.update(rects)

    # loop over the tracked objects
    for (objectID, centroid) in objects.items():

        # check to see if a trackable object exists for the current object ID
        to = trackableObjects.get(objectID, None)

        # if there is no existing trackable object, create one
        if to is None:
            to = TrackableObject(objectID, centroid)

        # otherwise, there is a trackable object so we can utilize it to determine direction
        else:
            # the difference between the y-coordinate of the *current*
            # centroid and the mean of *previous* centroids will tell
            # us in which direction the object is moving (negative for
            # 'up' and positive for 'down')
            y = [c[1] for c in to.centroids]
            direction = centroid[1] - np.mean(y)
            to.centroids.append(centroid)

            # check to see if the object has been counted or not
            if not to.counted:
                # if the direction is negative (indicating the object
                # is moving up) AND the centroid is above the center
                # line, count the object
                if direction < 0 and centroid[1] < H // 2:
#                     playsound('audios/audio.mp3')  #out sound
                    totalUp += 1
                    to.counted = True

                # if the direction is positive (indicating the object
                # is moving down) AND the centroid is below the
                # center line, count the object
                elif direction > 0 and centroid[1] > H // 2:
#                     playsound('audios/In.mp3')
                    totalDown += 1
                    to.counted = True

        # store the trackable object in our dictionary
        trackableObjects[objectID] = to

        # draw both the ID of the object and the centroid of the object on the output frame
        text = "ID {}".format(objectID)
        cv2.putText(frame, text, (centroid[0] - 10, centroid[1] - 10),
            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
        cv2.circle(frame, (centroid[0], centroid[1]), 4, (0, 255, 0), -1)

    # construct a tuple of information we will be displaying on the frame
    info = [
        ("Up", totalUp),
        ("Down", totalDown),
        ("Total",totalUp+totalDown),
        ("Status", status)
    ]

    # loop over the info tuples and draw them on our frame
    for (i, (k, v)) in enumerate(info):
        text = "{}: {}".format(k, v)
        cv2.putText(frame, text, (10, H - ((i * 20) + 20)),
            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

    # check to see if we should write the frame to disk
    if writer is not None:
        writer.write(frame)

    # show the output frame
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1) & 0xFF

    # if the `q` key was pressed, break from the loop
    if key == ord("q"):
        break

    # increment the total number of frames processed thus far and then update the FPS counter
    totalFrames += 1
    fps.update()


[[[151 148 149]
  [149 146 147]
  [147 144 145]
  ...
  [166 165 167]
  [167 167 167]
  [164 164 164]]

 [[151 148 149]
  [149 146 147]
  [147 144 145]
  ...
  [157 156 158]
  [156 156 156]
  [154 154 154]]

 [[151 148 149]
  [149 146 147]
  [147 144 145]
  ...
  [178 177 179]
  [174 174 174]
  [173 173 173]]

 ...

 [[148 144 147]
  [148 144 147]
  [147 143 146]
  ...
  [120 122 124]
  [111 111 111]
  [105 105 105]]

 [[148 144 147]
  [148 144 147]
  [147 143 146]
  ...
  [116 118 120]
  [111 111 111]
  [105 105 105]]

 [[148 144 147]
  [148 144 147]
  [147 143 146]
  ...
  [111 113 115]
  [111 111 111]
  [105 105 105]]]
the detection is [[[[0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0.

[[[145 144 146]
  [143 142 144]
  [139 138 140]
  ...
  [186 185 187]
  [188 188 188]
  [187 187 187]]

 [[145 144 146]
  [143 142 144]
  [139 138 140]
  ...
  [192 191 193]
  [189 189 189]
  [189 189 189]]

 [[146 145 147]
  [143 142 144]
  [139 138 140]
  ...
  [187 186 188]
  [187 187 187]
  [188 188 188]]

 ...

 [[149 146 147]
  [147 144 145]
  [147 144 145]
  ...
  [ 99 101 103]
  [ 95  98  98]
  [ 93  96  96]]

 [[151 146 147]
  [149 144 145]
  [149 144 145]
  ...
  [ 97  99 101]
  [ 94  97  97]
  [ 92  95  95]]

 [[151 146 147]
  [149 144 145]
  [149 144 145]
  ...
  [ 97  99 101]
  [ 95  98  98]
  [ 93  96  96]]]
[[[145 144 146]
  [143 142 144]
  [139 138 140]
  ...
  [183 186 186]
  [187 187 187]
  [186 186 186]]

 [[145 144 146]
  [143 142 144]
  [139 138 140]
  ...
  [185 188 188]
  [188 188 188]
  [188 188 188]]

 [[146 145 147]
  [143 142 144]
  [139 138 140]
  ...
  [190 193 193]
  [190 190 190]
  [192 192 192]]

 ...

 [[149 146 147]
  [147 144 145]
  [146 143 144]
  ..

[[[145 141 144]
  [141 137 140]
  [140 136 139]
  ...
  [183 183 183]
  [183 183 183]
  [183 183 183]]

 [[145 141 144]
  [142 138 141]
  [141 137 140]
  ...
  [186 186 186]
  [186 186 186]
  [185 185 185]]

 [[144 140 143]
  [142 138 141]
  [141 137 140]
  ...
  [189 189 189]
  [189 189 189]
  [187 187 187]]

 ...

 [[146 146 146]
  [144 144 144]
  [146 146 146]
  ...
  [ 98  98  98]
  [ 90  93  93]
  [ 79  82  82]]

 [[146 146 146]
  [146 146 146]
  [146 146 146]
  ...
  [ 98  98  98]
  [ 90  93  93]
  [ 79  82  82]]

 [[145 145 145]
  [144 144 144]
  [144 144 144]
  ...
  [100 100 100]
  [ 91  94  94]
  [ 82  85  85]]]
[[[146 142 145]
  [144 140 143]
  [144 140 143]
  ...
  [182 182 182]
  [183 183 183]
  [183 183 183]]

 [[146 142 145]
  [144 140 143]
  [144 140 143]
  ...
  [186 186 186]
  [186 186 186]
  [185 185 185]]

 [[145 141 144]
  [142 138 141]
  [142 138 141]
  ...
  [189 189 189]
  [189 189 189]
  [187 187 187]]

 ...

 [[146 146 146]
  [144 144 144]
  [146 146 146]
  ..

[[[147 144 145]
  [144 141 142]
  [145 142 143]
  ...
  [182 185 185]
  [183 183 183]
  [183 183 183]]

 [[147 144 145]
  [144 141 142]
  [145 142 143]
  ...
  [182 185 185]
  [185 185 185]
  [186 186 186]]

 [[146 143 144]
  [144 141 142]
  [145 142 143]
  ...
  [184 187 187]
  [188 188 188]
  [187 187 187]]

 ...

 [[146 146 146]
  [145 145 145]
  [147 147 147]
  ...
  [ 95  98  98]
  [ 91  94  94]
  [ 77  80  80]]

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ...
  [ 97 100  98]
  [ 88  91  91]
  [ 76  79  79]]

 [[145 145 145]
  [145 145 145]
  [144 144 144]
  ...
  [ 99 102 100]
  [ 90  93  93]
  [ 79  82  82]]]
[[[149 146 147]
  [147 144 145]
  [146 143 144]
  ...
  [185 185 185]
  [185 185 185]
  [185 185 185]]

 [[148 145 146]
  [146 143 144]
  [148 145 146]
  ...
  [185 185 185]
  [185 185 185]
  [186 186 186]]

 [[147 144 145]
  [145 142 143]
  [148 145 146]
  ...
  [187 187 187]
  [188 188 188]
  [187 187 187]]

 ...

 [[146 146 146]
  [145 145 145]
  [147 147 147]
  ..

[[[149 146 147]
  [148 145 146]
  [147 144 145]
  ...
  [186 186 186]
  [186 186 186]
  [186 186 186]]

 [[151 148 149]
  [148 145 146]
  [147 144 145]
  ...
  [188 188 188]
  [188 188 188]
  [187 187 187]]

 [[149 146 147]
  [148 145 146]
  [147 144 145]
  ...
  [182 182 182]
  [179 179 179]
  [179 179 179]]

 ...

 [[145 145 145]
  [146 146 146]
  [144 144 144]
  ...
  [ 94  96  98]
  [ 88  91  91]
  [ 79  82  82]]

 [[144 144 144]
  [144 144 144]
  [145 145 145]
  ...
  [ 97  99 101]
  [ 91  94  94]
  [ 82  85  85]]

 [[143 143 143]
  [143 143 143]
  [143 143 143]
  ...
  [ 98 100 102]
  [ 92  95  95]
  [ 84  87  87]]]
[[[149 146 147]
  [148 145 146]
  [147 144 145]
  ...
  [186 186 186]
  [186 186 186]
  [186 186 186]]

 [[151 148 149]
  [148 145 146]
  [147 144 145]
  ...
  [189 189 189]
  [188 188 188]
  [187 187 187]]

 [[151 148 149]
  [148 145 146]
  [147 144 145]
  ...
  [186 186 186]
  [185 185 185]
  [183 183 183]]

 ...

 [[145 145 145]
  [145 145 145]
  [142 142 142]
  ..

[[[149 146 147]
  [147 144 145]
  [147 144 145]
  ...
  [183 186 186]
  [186 186 186]
  [187 187 187]]

 [[149 146 147]
  [145 142 143]
  [146 143 144]
  ...
  [186 189 189]
  [189 189 189]
  [188 188 188]]

 [[149 146 147]
  [145 142 143]
  [146 143 144]
  ...
  [179 182 182]
  [180 180 180]
  [180 180 180]]

 ...

 [[146 143 144]
  [144 141 142]
  [145 142 143]
  ...
  [ 94  96  98]
  [ 88  91  91]
  [ 80  83  83]]

 [[145 142 143]
  [144 141 142]
  [145 142 143]
  ...
  [ 98 100 102]
  [ 88  91  91]
  [ 80  83  83]]

 [[145 142 143]
  [145 142 143]
  [146 143 144]
  ...
  [ 98 100 102]
  [ 92  95  95]
  [ 85  88  88]]]
[[[152 149 150]
  [149 146 147]
  [147 144 145]
  ...
  [186 186 186]
  [187 187 187]
  [187 187 187]]

 [[153 150 151]
  [149 146 147]
  [148 145 146]
  ...
  [188 188 188]
  [188 188 188]
  [186 186 186]]

 [[152 149 150]
  [149 146 147]
  [149 146 147]
  ...
  [176 176 176]
  [178 178 178]
  [176 176 176]]

 ...

 [[146 143 144]
  [144 141 142]
  [145 142 143]
  ..

[[[150 150 150]
  [147 147 147]
  [145 145 145]
  ...
  [182 185 185]
  [187 187 187]
  [185 185 185]]

 [[151 151 151]
  [146 146 146]
  [144 144 144]
  ...
  [189 192 192]
  [192 192 192]
  [189 189 189]]

 [[151 151 151]
  [146 146 146]
  [143 143 143]
  ...
  [177 180 180]
  [181 181 181]
  [178 178 178]]

 ...

 [[144 144 144]
  [144 144 144]
  [142 142 142]
  ...
  [ 95  98  98]
  [ 97 100 100]
  [ 92  95  95]]

 [[144 144 144]
  [143 143 143]
  [144 144 144]
  ...
  [ 93  98  98]
  [ 94  97  97]
  [ 91  94  94]]

 [[142 142 142]
  [140 140 140]
  [140 140 140]
  ...
  [ 95 100 100]
  [ 95  98  98]
  [ 92  95  95]]]
[[[151 151 151]
  [147 147 147]
  [145 145 145]
  ...
  [184 186 188]
  [188 188 188]
  [186 186 186]]

 [[152 152 152]
  [147 147 147]
  [145 145 145]
  ...
  [190 192 194]
  [193 193 193]
  [190 190 190]]

 [[151 151 151]
  [147 147 147]
  [144 144 144]
  ...
  [179 181 183]
  [182 182 182]
  [179 179 179]]

 ...

 [[144 144 144]
  [144 144 144]
  [142 142 142]
  ..

[[[149 149 149]
  [145 145 145]
  [144 144 144]
  ...
  [183 185 187]
  [187 187 187]
  [186 186 186]]

 [[150 150 150]
  [146 146 146]
  [143 143 143]
  ...
  [189 191 193]
  [190 190 190]
  [187 187 187]]

 [[150 150 150]
  [146 146 146]
  [142 142 142]
  ...
  [177 179 181]
  [179 179 179]
  [179 179 179]]

 ...

 [[145 142 143]
  [144 141 142]
  [142 139 140]
  ...
  [ 91  96  96]
  [ 90  95  95]
  [ 86  91  91]]

 [[145 142 143]
  [144 141 142]
  [142 139 140]
  ...
  [ 89  97  96]
  [ 90  95  95]
  [ 86  91  91]]

 [[145 142 143]
  [144 141 142]
  [142 139 140]
  ...
  [ 89  97  96]
  [ 90  95  95]
  [ 86  91  91]]]
[[[149 149 149]
  [145 145 145]
  [144 144 144]
  ...
  [183 185 187]
  [185 185 185]
  [185 185 185]]

 [[150 150 150]
  [146 146 146]
  [143 143 143]
  ...
  [190 192 194]
  [192 192 192]
  [192 192 192]]

 [[150 150 150]
  [146 146 146]
  [142 142 142]
  ...
  [177 179 181]
  [181 181 181]
  [180 180 180]]

 ...

 [[145 142 143]
  [144 141 142]
  [142 139 140]
  ..

[[[149 146 147]
  [147 144 145]
  [147 144 145]
  ...
  [184 187 187]
  [187 187 187]
  [185 185 185]]

 [[149 146 147]
  [147 144 145]
  [147 144 145]
  ...
  [187 190 190]
  [190 190 190]
  [189 189 189]]

 [[151 148 149]
  [148 145 146]
  [148 145 146]
  ...
  [176 179 179]
  [180 180 180]
  [179 179 179]]

 ...

 [[145 145 145]
  [144 144 144]
  [144 144 144]
  ...
  [ 97  99 101]
  [ 89  94  94]
  [ 80  85  85]]

 [[145 145 145]
  [145 145 145]
  [144 144 144]
  ...
  [ 98 100 102]
  [ 89  94  94]
  [ 82  87  87]]

 [[145 145 145]
  [144 144 144]
  [143 143 143]
  ...
  [ 97  99 101]
  [ 90  95  95]
  [ 85  90  90]]]
[[[148 145 146]
  [147 144 145]
  [147 144 145]
  ...
  [186 186 186]
  [189 189 189]
  [186 186 186]]

 [[151 148 149]
  [147 144 145]
  [148 145 146]
  ...
  [189 189 189]
  [190 190 190]
  [189 189 189]]

 [[153 150 151]
  [149 146 147]
  [148 145 146]
  ...
  [175 175 175]
  [176 176 176]
  [174 174 174]]

 ...

 [[145 145 145]
  [144 144 144]
  [144 144 144]
  ..

[[[153 150 151]
  [148 145 146]
  [146 143 144]
  ...
  [185 184 186]
  [183 183 183]
  [183 183 183]]

 [[153 150 151]
  [148 145 146]
  [146 143 144]
  ...
  [188 187 189]
  [189 189 189]
  [188 188 188]]

 [[154 151 152]
  [148 145 146]
  [145 142 143]
  ...
  [174 173 175]
  [173 173 173]
  [174 174 174]]

 ...

 [[147 147 147]
  [144 144 144]
  [145 145 145]
  ...
  [ 97  99 101]
  [ 91  94  94]
  [ 84  87  87]]

 [[147 147 147]
  [145 145 145]
  [145 145 145]
  ...
  [ 95  97  99]
  [ 92  95  95]
  [ 87  90  90]]

 [[145 145 145]
  [146 146 146]
  [146 146 146]
  ...
  [100 102 104]
  [ 95  98  98]
  [ 91  94  94]]]
[[[152 149 150]
  [148 145 146]
  [146 143 144]
  ...
  [186 185 187]
  [183 183 183]
  [183 183 183]]

 [[152 149 150]
  [148 145 146]
  [146 143 144]
  ...
  [190 189 191]
  [189 189 189]
  [188 188 188]]

 [[153 150 151]
  [148 145 146]
  [145 142 143]
  ...
  [174 173 175]
  [173 173 173]
  [174 174 174]]

 ...

 [[146 146 146]
  [145 145 145]
  [145 145 145]
  ..

[[[152 152 152]
  [146 146 146]
  [144 144 144]
  ...
  [184 187 187]
  [186 186 186]
  [183 183 183]]

 [[152 152 152]
  [146 146 146]
  [143 143 143]
  ...
  [182 185 185]
  [186 186 186]
  [183 183 183]]

 [[152 152 152]
  [147 147 147]
  [140 140 140]
  ...
  [161 164 164]
  [160 160 160]
  [161 161 161]]

 ...

 [[146 145 147]
  [146 145 147]
  [144 143 145]
  ...
  [ 98 100 102]
  [ 97 100 100]
  [ 93  96  96]]

 [[147 146 148]
  [145 144 146]
  [143 142 144]
  ...
  [ 99 101 103]
  [ 98 101 101]
  [ 93  96  96]]

 [[147 146 148]
  [147 146 148]
  [144 143 145]
  ...
  [102 104 106]
  [ 98 101 101]
  [ 95  98  98]]]
[[[152 152 152]
  [146 146 146]
  [144 144 144]
  ...
  [184 186 188]
  [186 186 186]
  [183 183 183]]

 [[151 151 151]
  [145 145 145]
  [142 142 142]
  ...
  [179 181 183]
  [186 186 186]
  [183 183 183]]

 [[151 151 151]
  [146 146 146]
  [139 139 139]
  ...
  [158 160 162]
  [160 160 160]
  [161 161 161]]

 ...

 [[147 146 148]
  [146 145 147]
  [145 144 146]
  ..

[[[156 153 154]
  [151 148 149]
  [147 144 145]
  ...
  [189 191 193]
  [190 190 190]
  [188 188 188]]

 [[159 156 157]
  [153 150 151]
  [147 144 145]
  ...
  [170 172 174]
  [172 172 172]
  [173 173 173]]

 [[156 153 154]
  [153 150 151]
  [146 143 144]
  ...
  [155 157 159]
  [157 157 157]
  [157 157 157]]

 ...

 [[146 145 147]
  [146 145 147]
  [145 144 146]
  ...
  [101 103 105]
  [ 97 100 100]
  [ 95  98  98]]

 [[146 145 147]
  [146 145 147]
  [146 145 147]
  ...
  [102 104 106]
  [ 99 102 102]
  [ 95  98  98]]

 [[145 144 146]
  [145 144 146]
  [144 143 145]
  ...
  [102 104 106]
  [ 99 102 102]
  [ 97 100 100]]]
[[[156 153 154]
  [152 149 150]
  [147 144 145]
  ...
  [186 188 190]
  [189 189 189]
  [187 187 187]]

 [[159 156 157]
  [152 149 150]
  [147 144 145]
  ...
  [168 170 172]
  [171 171 171]
  [172 172 172]]

 [[158 155 156]
  [153 150 151]
  [147 144 145]
  ...
  [156 158 160]
  [158 158 158]
  [158 158 158]]

 ...

 [[146 145 147]
  [146 145 147]
  [145 144 146]
  ..

[[[155 152 153]
  [148 145 146]
  [145 142 143]
  ...
  [182 184 186]
  [186 186 186]
  [182 182 182]]

 [[155 152 153]
  [151 148 149]
  [145 142 143]
  ...
  [160 162 164]
  [160 160 160]
  [159 159 159]]

 [[154 151 152]
  [151 148 149]
  [145 142 143]
  ...
  [164 166 168]
  [166 166 166]
  [168 168 168]]

 ...

 [[146 142 145]
  [147 143 146]
  [146 145 147]
  ...
  [101 102 107]
  [ 95 100 100]
  [ 90  95  95]]

 [[145 141 144]
  [146 142 145]
  [144 143 145]
  ...
  [101 103 105]
  [ 95 100 100]
  [ 93  98  98]]

 [[146 142 145]
  [142 138 141]
  [140 139 141]
  ...
  [ 99 101 103]
  [ 95 100 100]
  [ 92  97  97]]]
[[[153 153 153]
  [147 147 147]
  [143 143 143]
  ...
  [180 182 184]
  [185 185 185]
  [183 183 183]]

 [[154 154 154]
  [150 150 150]
  [144 144 144]
  ...
  [158 160 162]
  [159 159 159]
  [158 158 158]]

 [[153 153 153]
  [150 150 150]
  [144 144 144]
  ...
  [162 164 166]
  [165 165 165]
  [166 166 166]]

 ...

 [[146 142 145]
  [147 143 146]
  [146 145 147]
  ..

[[[153 150 151]
  [151 148 149]
  [145 142 143]
  ...
  [182 184 186]
  [185 185 185]
  [183 183 183]]

 [[156 153 154]
  [153 150 151]
  [145 142 143]
  ...
  [158 160 162]
  [163 163 163]
  [161 161 161]]

 [[158 155 156]
  [154 151 152]
  [146 143 144]
  ...
  [161 163 165]
  [164 164 164]
  [164 164 164]]

 ...

 [[147 144 145]
  [148 145 146]
  [148 145 146]
  ...
  [ 99 101 103]
  [ 95  98 103]
  [ 93  96 101]]

 [[146 143 144]
  [146 143 144]
  [147 144 145]
  ...
  [ 98 102 104]
  [ 95  98 103]
  [ 93  96 101]]

 [[145 142 143]
  [145 142 143]
  [145 142 143]
  ...
  [ 98 102 104]
  [ 95  98 103]
  [ 95  98 103]]]
[[[153 150 151]
  [149 146 147]
  [147 144 145]
  ...
  [182 184 186]
  [185 185 185]
  [183 183 183]]

 [[155 152 153]
  [152 149 150]
  [147 144 145]
  ...
  [158 160 162]
  [163 163 163]
  [161 161 161]]

 [[156 153 154]
  [152 149 150]
  [147 144 145]
  ...
  [160 162 164]
  [164 164 164]
  [164 164 164]]

 ...

 [[147 144 145]
  [148 145 146]
  [148 145 146]
  ..

[[[155 152 153]
  [152 149 150]
  [145 142 143]
  ...
  [174 173 175]
  [174 174 174]
  [174 174 174]]

 [[158 155 156]
  [151 148 149]
  [144 141 142]
  ...
  [152 151 153]
  [153 153 153]
  [154 154 154]]

 [[155 152 153]
  [149 146 147]
  [146 143 144]
  ...
  [168 167 169]
  [170 170 170]
  [174 174 174]]

 ...

 [[146 143 144]
  [146 143 144]
  [145 142 143]
  ...
  [ 99 101 103]
  [ 96  99 104]
  [ 93  96 101]]

 [[147 143 146]
  [146 142 145]
  [145 141 144]
  ...
  [ 96 100 102]
  [ 96  99 104]
  [ 93  96 101]]

 [[145 141 144]
  [144 140 143]
  [142 138 141]
  ...
  [ 97 101 103]
  [ 96  99 104]
  [ 95  98 103]]]
[[[153 150 151]
  [149 146 147]
  [144 141 142]
  ...
  [174 173 175]
  [173 173 173]
  [172 172 172]]

 [[154 151 152]
  [147 144 145]
  [142 139 140]
  ...
  [152 151 153]
  [152 152 152]
  [156 156 156]]

 [[152 149 150]
  [147 144 145]
  [145 142 143]
  ...
  [167 166 168]
  [170 170 170]
  [174 174 174]]

 ...

 [[146 143 144]
  [146 143 144]
  [145 142 143]
  ..

[[[155 152 153]
  [152 149 150]
  [146 143 144]
  ...
  [188 187 189]
  [192 192 192]
  [190 190 190]]

 [[156 153 154]
  [151 148 149]
  [144 141 142]
  ...
  [165 164 166]
  [166 166 166]
  [164 164 164]]

 [[156 153 154]
  [151 148 149]
  [145 142 143]
  ...
  [156 155 157]
  [153 153 153]
  [156 156 156]]

 ...

 [[150 145 146]
  [149 144 145]
  [149 144 145]
  ...
  [100 102 104]
  [ 95  99 101]
  [ 91  95  97]]

 [[149 145 148]
  [149 145 148]
  [147 143 146]
  ...
  [ 98 102 104]
  [ 93  97  99]
  [ 92  96  98]]

 [[149 145 148]
  [148 144 147]
  [146 142 145]
  ...
  [ 99 103 105]
  [ 96 100 102]
  [ 95  99 101]]]
[[[154 151 152]
  [151 148 149]
  [145 142 143]
  ...
  [188 187 189]
  [192 192 192]
  [190 190 190]]

 [[155 152 153]
  [151 148 149]
  [144 141 142]
  ...
  [166 165 167]
  [166 166 166]
  [164 164 164]]

 [[155 152 153]
  [149 146 147]
  [144 141 142]
  ...
  [154 153 155]
  [153 153 153]
  [156 156 156]]

 ...

 [[150 145 146]
  [149 144 145]
  [149 144 145]
  ..

[[[153 150 151]
  [147 144 145]
  [145 142 143]
  ...
  [188 187 189]
  [188 188 188]
  [188 188 188]]

 [[154 151 152]
  [147 144 145]
  [144 141 142]
  ...
  [175 174 176]
  [173 173 173]
  [172 172 172]]

 [[155 152 153]
  [146 143 144]
  [144 141 142]
  ...
  [161 160 162]
  [159 159 159]
  [159 159 159]]

 ...

 [[151 146 147]
  [150 145 146]
  [150 145 146]
  ...
  [ 99 101 103]
  [ 92  96  98]
  [ 84  88  90]]

 [[149 146 147]
  [148 145 146]
  [146 143 144]
  ...
  [ 95  99 101]
  [ 90  94  96]
  [ 88  92  94]]

 [[148 145 146]
  [146 143 144]
  [145 142 143]
  ...
  [ 93  97  99]
  [ 90  94  96]
  [ 91  95  97]]]
[[[154 151 152]
  [148 145 146]
  [146 143 144]
  ...
  [189 188 190]
  [189 189 189]
  [188 188 188]]

 [[153 150 151]
  [146 143 144]
  [144 141 142]
  ...
  [178 177 179]
  [176 176 176]
  [174 174 174]]

 [[154 151 152]
  [145 142 143]
  [142 139 140]
  ...
  [161 160 162]
  [163 163 163]
  [161 161 161]]

 ...

 [[151 146 147]
  [150 145 146]
  [150 145 146]
  ..

[[[154 151 152]
  [148 145 146]
  [147 144 145]
  ...
  [187 187 187]
  [187 187 187]
  [187 187 187]]

 [[154 151 152]
  [148 145 146]
  [145 142 143]
  ...
  [186 186 186]
  [185 185 185]
  [185 185 185]]

 [[154 151 152]
  [149 146 147]
  [145 142 143]
  ...
  [161 161 161]
  [160 160 160]
  [163 163 163]]

 ...

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ...
  [102 101 103]
  [ 97 101 103]
  [ 96 100 102]]

 [[145 145 145]
  [146 146 146]
  [146 146 146]
  ...
  [100 102 104]
  [ 97 101 103]
  [ 92  96  98]]

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ...
  [102 104 106]
  [ 97 101 103]
  [ 93  97  99]]]
[[[153 150 151]
  [151 148 149]
  [149 146 147]
  ...
  [188 187 189]
  [188 188 188]
  [189 189 189]]

 [[154 151 152]
  [151 148 149]
  [145 142 143]
  ...
  [180 179 181]
  [180 180 180]
  [181 181 181]]

 [[153 150 151]
  [149 146 147]
  [144 141 142]
  ...
  [157 156 158]
  [158 158 158]
  [159 159 159]]

 ...

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ..

[[[152 152 152]
  [149 149 149]
  [145 145 145]
  ...
  [193 193 193]
  [192 192 192]
  [188 188 188]]

 [[153 153 153]
  [147 147 147]
  [143 143 143]
  ...
  [181 181 181]
  [181 181 181]
  [179 179 179]]

 [[153 153 153]
  [147 147 147]
  [143 143 143]
  ...
  [159 159 159]
  [160 160 160]
  [160 160 160]]

 ...

 [[146 145 147]
  [145 144 146]
  [145 144 146]
  ...
  [ 95  94  96]
  [ 95  97  99]
  [ 90  92  94]]

 [[146 145 147]
  [145 144 146]
  [145 144 146]
  ...
  [ 92  94  96]
  [ 94  96  98]
  [ 93  95  97]]

 [[145 144 146]
  [144 143 145]
  [144 143 145]
  ...
  [ 97  99 101]
  [ 95  97  99]
  [ 95  97  99]]]
[[[152 152 152]
  [149 149 149]
  [144 144 144]
  ...
  [193 193 193]
  [192 192 192]
  [189 189 189]]

 [[153 153 153]
  [147 147 147]
  [142 142 142]
  ...
  [178 178 178]
  [180 180 180]
  [180 180 180]]

 [[152 152 152]
  [146 146 146]
  [143 143 143]
  ...
  [158 158 158]
  [160 160 160]
  [159 159 159]]

 ...

 [[146 145 147]
  [145 144 146]
  [145 144 146]
  ..

[[[153 150 151]
  [148 145 146]
  [148 145 146]
  ...
  [190 193 193]
  [192 192 192]
  [188 188 188]]

 [[153 150 151]
  [148 145 146]
  [146 143 144]
  ...
  [177 180 180]
  [176 176 176]
  [175 175 175]]

 [[152 149 150]
  [147 144 145]
  [146 143 144]
  ...
  [156 159 159]
  [158 158 158]
  [158 158 158]]

 ...

 [[149 145 148]
  [147 143 146]
  [147 143 146]
  ...
  [100 101 106]
  [ 95  97  99]
  [ 94  96  98]]

 [[147 143 146]
  [147 143 146]
  [146 142 145]
  ...
  [ 99 102 107]
  [ 95  97  99]
  [ 93  95  97]]

 [[145 141 144]
  [145 141 144]
  [146 142 145]
  ...
  [ 98 101 106]
  [ 98 100 102]
  [ 95  97  99]]]
[[[152 149 150]
  [147 144 145]
  [146 143 144]
  ...
  [190 193 193]
  [192 192 192]
  [188 188 188]]

 [[153 150 151]
  [148 145 146]
  [145 142 143]
  ...
  [177 180 180]
  [176 176 176]
  [175 175 175]]

 [[153 150 151]
  [148 145 146]
  [146 143 144]
  ...
  [156 159 159]
  [158 158 158]
  [158 158 158]]

 ...

 [[149 145 148]
  [147 143 146]
  [147 143 146]
  ..

[[[147 144 145]
  [147 144 145]
  [148 145 146]
  ...
  [188 188 188]
  [187 187 187]
  [186 186 186]]

 [[147 144 145]
  [146 143 144]
  [147 144 145]
  ...
  [186 186 186]
  [187 187 187]
  [186 186 186]]

 [[146 143 144]
  [144 141 142]
  [147 144 145]
  ...
  [168 168 168]
  [166 166 166]
  [167 167 167]]

 ...

 [[148 145 146]
  [147 144 145]
  [146 143 144]
  ...
  [ 90  92  94]
  [ 82  87  87]
  [ 69  74  74]]

 [[147 144 145]
  [146 143 144]
  [145 142 143]
  ...
  [ 89  93  95]
  [ 86  91  91]
  [ 76  81  81]]

 [[147 144 145]
  [146 143 144]
  [145 142 143]
  ...
  [ 91  95  97]
  [ 88  93  93]
  [ 80  85  85]]]
the detection is [[[[0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0.

[[[149 145 148]
  [145 141 144]
  [141 137 140]
  ...
  [182 184 186]
  [185 185 185]
  [185 185 185]]

 [[148 144 147]
  [144 140 143]
  [141 137 140]
  ...
  [185 187 189]
  [186 186 186]
  [186 186 186]]

 [[148 144 147]
  [144 140 143]
  [139 135 138]
  ...
  [171 173 175]
  [174 174 174]
  [174 174 174]]

 ...

 [[146 146 146]
  [145 145 145]
  [144 144 144]
  ...
  [ 93  92  94]
  [ 91  96  96]
  [ 89  94  94]]

 [[145 145 145]
  [144 144 144]
  [145 145 145]
  ...
  [ 98  97  99]
  [ 90  95  95]
  [ 89  94  94]]

 [[145 145 145]
  [144 144 144]
  [145 145 145]
  ...
  [102 101 103]
  [ 95 100 100]
  [ 91  96  96]]]
[[[151 145 148]
  [147 141 144]
  [143 137 140]
  ...
  [182 184 186]
  [186 186 186]
  [185 185 185]]

 [[150 144 147]
  [146 140 143]
  [142 136 139]
  ...
  [187 189 191]
  [186 186 186]
  [187 187 187]]

 [[151 145 148]
  [147 141 144]
  [141 135 138]
  ...
  [168 170 172]
  [170 170 170]
  [167 167 167]]

 ...

 [[146 146 146]
  [145 145 145]
  [144 144 144]
  ..

[[[146 142 145]
  [144 140 143]
  [142 138 141]
  ...
  [190 189 191]
  [192 192 192]
  [193 193 193]]

 [[148 144 147]
  [144 140 143]
  [140 136 139]
  ...
  [170 169 171]
  [172 172 172]
  [172 172 172]]

 [[148 144 147]
  [145 141 144]
  [141 137 140]
  ...
  [154 153 155]
  [156 156 156]
  [157 157 157]]

 ...

 [[146 146 146]
  [145 145 145]
  [144 144 144]
  ...
  [103 102 104]
  [ 94  97  97]
  [ 88  91  91]]

 [[146 146 146]
  [146 146 146]
  [145 145 145]
  ...
  [103 102 104]
  [ 94  97  97]
  [ 91  94  94]]

 [[145 145 145]
  [144 144 144]
  [143 143 143]
  ...
  [103 102 104]
  [ 98 101 101]
  [ 93  96  96]]]
[[[145 141 144]
  [145 141 144]
  [144 140 143]
  ...
  [189 188 190]
  [188 188 188]
  [189 189 189]]

 [[148 144 147]
  [144 140 143]
  [140 136 139]
  ...
  [170 169 171]
  [168 168 168]
  [168 168 168]]

 [[148 144 147]
  [145 141 144]
  [141 137 140]
  ...
  [154 153 155]
  [157 157 157]
  [157 157 157]]

 ...

 [[146 146 146]
  [145 145 145]
  [144 144 144]
  ..

[[[149 146 147]
  [145 142 143]
  [140 137 138]
  ...
  [186 185 187]
  [181 181 181]
  [180 180 180]]

 [[151 148 149]
  [145 142 143]
  [142 139 140]
  ...
  [159 158 160]
  [160 160 160]
  [159 159 159]]

 [[149 146 147]
  [146 143 144]
  [144 141 142]
  ...
  [168 167 169]
  [170 170 170]
  [170 170 170]]

 ...

 [[147 147 147]
  [147 147 147]
  [145 145 145]
  ...
  [101 103 105]
  [ 97 102 102]
  [ 92  97  97]]

 [[145 145 145]
  [145 145 145]
  [144 144 144]
  ...
  [ 96 100 102]
  [ 92  97  97]
  [ 93  98  98]]

 [[145 145 145]
  [145 145 145]
  [142 142 142]
  ...
  [ 96 100 102]
  [ 92  97  97]
  [ 91  96  96]]]
[[[148 145 146]
  [142 139 140]
  [138 135 136]
  ...
  [177 179 181]
  [180 180 180]
  [180 180 180]]

 [[149 146 147]
  [142 139 140]
  [140 137 138]
  ...
  [155 157 159]
  [159 159 159]
  [159 159 159]]

 [[148 145 146]
  [144 141 142]
  [141 138 139]
  ...
  [165 167 169]
  [170 170 170]
  [168 168 168]]

 ...

 [[147 147 147]
  [147 147 147]
  [146 146 146]
  ..

the detection is [[[[0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.

[[[149 145 148]
  [144 140 143]
  [139 135 138]
  ...
  [163 162 164]
  [163 163 163]
  [163 163 163]]

 [[149 145 148]
  [144 140 143]
  [139 135 138]
  ...
  [154 153 155]
  [154 154 154]
  [156 156 156]]

 [[149 145 148]
  [144 140 143]
  [139 135 138]
  ...
  [180 179 181]
  [180 180 180]
  [181 181 181]]

 ...

 [[146 146 146]
  [146 146 146]
  [145 145 145]
  ...
  [105 107 109]
  [ 96 101 101]
  [ 92  97  97]]

 [[146 146 146]
  [145 145 145]
  [144 144 144]
  ...
  [ 98 102 104]
  [ 92  97  97]
  [ 90  95  95]]

 [[146 146 146]
  [145 145 145]
  [143 143 143]
  ...
  [ 97 101 103]
  [ 92  97  97]
  [ 92  97  97]]]
[[[148 145 146]
  [141 138 139]
  [137 134 135]
  ...
  [164 163 165]
  [165 165 165]
  [164 164 164]]

 [[147 144 145]
  [142 139 140]
  [138 135 136]
  ...
  [154 153 155]
  [154 154 154]
  [156 156 156]]

 [[147 144 145]
  [142 139 140]
  [138 135 136]
  ...
  [179 178 180]
  [179 179 179]
  [180 180 180]]

 ...

 [[144 144 144]
  [143 143 143]
  [143 143 143]
  ..

[[[145 142 143]
  [140 137 138]
  [137 134 135]
  ...
  [163 163 163]
  [165 165 165]
  [164 164 164]]

 [[144 141 142]
  [139 136 137]
  [135 132 133]
  ...
  [157 157 157]
  [159 159 159]
  [160 160 160]]

 [[146 143 144]
  [141 138 139]
  [139 136 137]
  ...
  [179 179 179]
  [181 181 181]
  [180 180 180]]

 ...

 [[145 145 145]
  [145 145 145]
  [144 144 144]
  ...
  [ 98 103 103]
  [ 90  95  95]
  [ 89  94  94]]

 [[144 144 144]
  [143 143 143]
  [144 144 144]
  ...
  [ 97 102 102]
  [ 91  96  96]
  [ 90  95  95]]

 [[144 144 144]
  [143 143 143]
  [142 142 142]
  ...
  [ 97 102 102]
  [ 91  96  96]
  [ 92  97  97]]]
[[[146 143 144]
  [141 138 139]
  [138 135 136]
  ...
  [159 159 159]
  [160 160 160]
  [160 160 160]]

 [[145 142 143]
  [140 137 138]
  [137 134 135]
  ...
  [156 156 156]
  [159 159 159]
  [159 159 159]]

 [[147 144 145]
  [141 138 139]
  [140 137 138]
  ...
  [182 182 182]
  [182 182 182]
  [182 182 182]]

 ...

 [[146 146 146]
  [145 145 145]
  [144 144 144]
  ..

[[[147 144 145]
  [144 141 142]
  [139 136 137]
  ...
  [160 159 161]
  [159 159 159]
  [158 158 158]]

 [[146 143 144]
  [142 139 140]
  [139 136 137]
  ...
  [157 156 158]
  [154 154 154]
  [154 154 154]]

 [[146 143 144]
  [141 138 139]
  [140 137 138]
  ...
  [180 179 181]
  [181 181 181]
  [182 182 182]]

 ...

 [[149 146 147]
  [148 145 146]
  [145 145 145]
  ...
  [101 103 105]
  [ 93  96  96]
  [ 92  95  95]]

 [[147 144 145]
  [147 144 145]
  [144 144 144]
  ...
  [100 102 104]
  [ 93  96  96]
  [ 92  95  95]]

 [[147 144 145]
  [146 143 144]
  [142 142 142]
  ...
  [ 99 101 103]
  [ 93  96  96]
  [ 92  95  95]]]
[[[146 143 144]
  [142 139 140]
  [137 134 135]
  ...
  [156 155 157]
  [156 156 156]
  [154 154 154]]

 [[146 143 144]
  [141 138 139]
  [138 135 136]
  ...
  [163 162 164]
  [160 160 160]
  [161 161 161]]

 [[147 144 145]
  [142 139 140]
  [140 137 138]
  ...
  [186 185 187]
  [187 187 187]
  [187 187 187]]

 ...

 [[149 146 147]
  [149 146 147]
  [145 145 145]
  ..

[[[148 143 142]
  [144 139 138]
  [142 137 138]
  ...
  [159 158 160]
  [159 159 159]
  [159 159 159]]

 [[150 145 144]
  [147 142 141]
  [143 138 139]
  ...
  [153 152 154]
  [156 156 156]
  [157 157 157]]

 [[151 146 145]
  [147 142 141]
  [143 138 139]
  ...
  [180 179 181]
  [181 181 181]
  [182 182 182]]

 ...

 [[148 143 144]
  [146 141 142]
  [145 142 143]
  ...
  [ 98 100 102]
  [ 91  94  94]
  [ 87  90  90]]

 [[147 142 143]
  [147 142 143]
  [145 142 143]
  ...
  [ 98 102 104]
  [ 93  96  96]
  [ 91  94  94]]

 [[148 143 144]
  [147 142 143]
  [144 141 142]
  ...
  [ 96 100 102]
  [ 92  95  95]
  [ 92  95  95]]]
[[[148 143 144]
  [144 139 140]
  [142 136 139]
  ...
  [159 158 160]
  [159 159 159]
  [159 159 159]]

 [[150 145 146]
  [147 142 143]
  [143 137 140]
  ...
  [153 152 154]
  [156 156 156]
  [157 157 157]]

 [[151 146 147]
  [147 142 143]
  [143 137 140]
  ...
  [180 179 181]
  [181 181 181]
  [182 182 182]]

 ...

 [[148 143 144]
  [146 141 142]
  [145 142 143]
  ..

[[[157 152 153]
  [155 150 151]
  [150 144 147]
  ...
  [159 158 160]
  [158 158 158]
  [158 158 158]]

 [[157 152 153]
  [155 150 151]
  [150 144 147]
  ...
  [157 156 158]
  [157 157 157]
  [157 157 157]]

 [[157 152 153]
  [154 149 150]
  [151 145 148]
  ...
  [180 179 181]
  [179 179 179]
  [179 179 179]]

 ...

 [[144 139 140]
  [144 139 140]
  [142 139 140]
  ...
  [ 99 101 103]
  [ 91  94  94]
  [ 91  94  94]]

 [[144 139 140]
  [144 139 140]
  [141 138 139]
  ...
  [ 98 100 102]
  [ 92  95  95]
  [ 92  95  95]]

 [[146 141 142]
  [144 139 140]
  [139 136 137]
  ...
  [ 98 100 102]
  [ 93  96  96]
  [ 94  97  97]]]
[[[156 151 152]
  [154 149 150]
  [149 143 146]
  ...
  [161 160 162]
  [163 163 163]
  [161 161 161]]

 [[156 151 152]
  [154 149 150]
  [149 143 146]
  ...
  [152 151 153]
  [152 152 152]
  [153 153 153]]

 [[156 151 152]
  [153 148 149]
  [150 144 147]
  ...
  [173 172 174]
  [175 175 175]
  [174 174 174]]

 ...

 [[144 139 140]
  [144 139 140]
  [142 139 140]
  ..

[[[155 152 153]
  [155 152 153]
  [151 147 150]
  ...
  [160 156 159]
  [161 161 161]
  [163 163 163]]

 [[158 155 156]
  [160 157 158]
  [152 148 151]
  ...
  [183 179 182]
  [182 182 182]
  [185 185 185]]

 [[156 153 154]
  [155 152 153]
  [151 147 150]
  ...
  [189 185 188]
  [189 189 189]
  [190 190 190]]

 ...

 [[144 140 143]
  [144 140 143]
  [140 139 141]
  ...
  [109 108 110]
  [100 102 104]
  [ 93  95  97]]

 [[142 138 141]
  [141 137 140]
  [139 138 140]
  ...
  [106 108 110]
  [101 103 105]
  [ 97  99 101]]

 [[144 140 143]
  [142 138 141]
  [138 137 139]
  ...
  [104 106 108]
  [100 102 104]
  [ 98 100 102]]]
[[[155 152 153]
  [155 152 153]
  [151 147 150]
  ...
  [159 155 158]
  [158 158 158]
  [159 159 159]]

 [[159 156 157]
  [159 156 157]
  [151 147 150]
  ...
  [177 173 176]
  [176 176 176]
  [179 179 179]]

 [[155 152 153]
  [156 153 154]
  [152 148 151]
  ...
  [190 186 189]
  [189 189 189]
  [192 192 192]]

 ...

 [[144 140 143]
  [144 140 143]
  [140 139 141]
  ..

[[[154 151 150]
  [154 151 150]
  [148 145 146]
  ...
  [154 153 155]
  [158 158 158]
  [157 157 157]]

 [[156 153 152]
  [155 152 151]
  [148 145 146]
  ...
  [176 175 177]
  [178 178 178]
  [176 176 176]]

 [[156 153 152]
  [155 152 151]
  [151 148 149]
  ...
  [194 193 195]
  [192 192 192]
  [192 192 192]]

 ...

 [[145 142 143]
  [145 142 143]
  [144 141 142]
  ...
  [108 109 114]
  [100 102 104]
  [ 92  94  96]]

 [[144 141 142]
  [144 141 142]
  [141 138 139]
  ...
  [104 107 112]
  [ 98 100 102]
  [ 94  96  98]]

 [[145 142 143]
  [145 142 143]
  [142 139 140]
  ...
  [103 106 111]
  [ 98 100 102]
  [ 95  97  99]]]
[[[154 151 150]
  [155 152 151]
  [151 148 149]
  ...
  [154 153 155]
  [158 158 158]
  [157 157 157]]

 [[156 153 152]
  [156 153 152]
  [151 148 149]
  ...
  [175 174 176]
  [178 178 178]
  [176 176 176]]

 [[156 153 152]
  [156 153 152]
  [152 149 150]
  ...
  [192 191 193]
  [192 192 192]
  [192 192 192]]

 ...

 [[145 142 143]
  [145 142 143]
  [142 139 140]
  ..

[[[156 153 152]
  [154 151 150]
  [148 145 146]
  ...
  [153 155 157]
  [158 158 158]
  [158 158 158]]

 [[154 151 150]
  [152 149 148]
  [146 143 144]
  ...
  [157 159 161]
  [161 161 161]
  [160 160 160]]

 [[154 151 150]
  [152 149 148]
  [148 145 146]
  ...
  [184 186 188]
  [188 188 188]
  [188 188 188]]

 ...

 [[142 139 140]
  [141 138 139]
  [141 137 140]
  ...
  [104 105 110]
  [ 95  98  98]
  [ 91  94  94]]

 [[144 141 142]
  [141 138 139]
  [139 135 138]
  ...
  [102 103 108]
  [ 97 100 100]
  [ 93  96  96]]

 [[144 141 142]
  [142 139 140]
  [140 136 139]
  ...
  [101 102 107]
  [ 95  98  98]
  [ 94  97  97]]]
[[[155 152 153]
  [153 150 151]
  [149 146 147]
  ...
  [153 155 157]
  [157 157 157]
  [157 157 157]]

 [[155 152 153]
  [151 148 149]
  [145 142 143]
  ...
  [157 159 161]
  [160 160 160]
  [160 160 160]]

 [[155 152 153]
  [151 148 149]
  [146 143 144]
  ...
  [182 184 186]
  [188 188 188]
  [188 188 188]]

 ...

 [[142 139 140]
  [141 138 139]
  [141 137 140]
  ..

[[[155 151 154]
  [153 149 152]
  [145 141 144]
  ...
  [151 153 155]
  [154 154 154]
  [156 156 156]]

 [[155 151 154]
  [153 149 152]
  [146 142 145]
  ...
  [158 160 162]
  [161 161 161]
  [163 163 163]]

 [[155 151 154]
  [152 148 151]
  [146 142 145]
  ...
  [187 186 188]
  [188 188 188]
  [187 187 187]]

 ...

 [[147 143 146]
  [146 142 145]
  [146 142 145]
  ...
  [ 98 101 106]
  [ 86  94  93]
  [ 84  92  91]]

 [[148 144 147]
  [146 142 145]
  [145 141 144]
  ...
  [ 97 101 103]
  [ 89  94  94]
  [ 86  91  91]]

 [[147 143 146]
  [145 141 144]
  [145 141 144]
  ...
  [ 97 101 103]
  [ 92  97  97]
  [ 90  95  95]]]
[[[154 150 153]
  [149 145 148]
  [142 138 141]
  ...
  [157 159 161]
  [160 160 160]
  [160 160 160]]

 [[154 150 153]
  [151 147 150]
  [144 140 143]
  ...
  [155 157 159]
  [159 159 159]
  [160 160 160]]

 [[153 149 152]
  [149 145 148]
  [145 141 144]
  ...
  [185 184 186]
  [183 183 183]
  [182 182 182]]

 ...

 [[147 143 146]
  [146 142 145]
  [146 142 145]
  ..

[[[154 151 152]
  [152 149 150]
  [146 143 144]
  ...
  [170 170 170]
  [171 171 171]
  [172 172 172]]

 [[155 152 153]
  [152 149 150]
  [146 143 144]
  ...
  [156 156 156]
  [154 154 154]
  [157 157 157]]

 [[155 152 153]
  [152 149 150]
  [147 144 145]
  ...
  [179 179 179]
  [175 175 175]
  [174 174 174]]

 ...

 [[145 144 146]
  [144 143 145]
  [142 141 143]
  ...
  [102 103 108]
  [101 104 104]
  [ 98 101 101]]

 [[145 144 146]
  [144 143 145]
  [143 142 144]
  ...
  [100 102 104]
  [105 105 105]
  [102 102 102]]

 [[147 146 148]
  [145 144 146]
  [143 142 144]
  ...
  [101 103 105]
  [103 103 103]
  [102 102 102]]]
[[[155 152 153]
  [152 149 150]
  [146 143 144]
  ...
  [166 166 166]
  [170 170 170]
  [171 171 171]]

 [[155 152 153]
  [151 148 149]
  [145 142 143]
  ...
  [152 152 152]
  [153 153 153]
  [153 153 153]]

 [[155 152 153]
  [151 148 149]
  [146 143 144]
  ...
  [175 175 175]
  [174 174 174]
  [175 175 175]]

 ...

 [[145 144 146]
  [144 143 145]
  [142 141 143]
  ..

[[[152 152 152]
  [150 150 150]
  [145 145 145]
  ...
  [173 170 171]
  [172 172 172]
  [168 168 168]]

 [[154 154 154]
  [150 150 150]
  [145 145 145]
  ...
  [155 152 153]
  [151 151 151]
  [152 152 152]]

 [[154 154 154]
  [151 151 151]
  [146 146 146]
  ...
  [167 167 167]
  [166 166 166]
  [168 168 168]]

 ...

 [[147 145 150]
  [146 144 149]
  [144 142 147]
  ...
  [102 108 112]
  [ 96 101 101]
  [ 90  95  95]]

 [[147 145 150]
  [146 144 149]
  [145 143 148]
  ...
  [101 108 109]
  [ 92  97  97]
  [ 91  96  96]]

 [[146 144 149]
  [144 142 147]
  [142 140 145]
  ...
  [100 107 108]
  [ 91  96  96]
  [ 89  94  94]]]
[[[154 154 154]
  [151 151 151]
  [145 145 145]
  ...
  [174 171 172]
  [174 174 174]
  [171 171 171]]

 [[154 154 154]
  [150 150 150]
  [145 145 145]
  ...
  [154 151 152]
  [152 152 152]
  [152 152 152]]

 [[154 154 154]
  [151 151 151]
  [146 146 146]
  ...
  [170 170 170]
  [171 171 171]
  [171 171 171]]

 ...

 [[147 145 150]
  [146 144 149]
  [144 142 147]
  ..

[[[153 153 153]
  [153 153 153]
  [146 146 146]
  ...
  [191 187 190]
  [192 192 192]
  [189 189 189]]

 [[153 153 153]
  [151 151 151]
  [144 144 144]
  ...
  [183 179 182]
  [183 183 183]
  [181 181 181]]

 [[154 154 154]
  [152 152 152]
  [145 145 145]
  ...
  [157 156 158]
  [158 158 158]
  [158 158 158]]

 ...

 [[146 146 146]
  [146 146 146]
  [145 145 145]
  ...
  [104 102 107]
  [ 90  95  95]
  [ 89  94  94]]

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ...
  [102 104 106]
  [ 96  96  96]
  [ 97  97  97]]

 [[146 146 146]
  [146 146 146]
  [144 144 144]
  ...
  [106 108 110]
  [ 97  97  97]
  [ 97  97  97]]]
[[[154 154 154]
  [152 152 152]
  [145 145 145]
  ...
  [191 187 190]
  [192 192 192]
  [189 189 189]]

 [[153 153 153]
  [150 150 150]
  [143 143 143]
  ...
  [183 179 182]
  [183 183 183]
  [181 181 181]]

 [[153 153 153]
  [150 150 150]
  [143 143 143]
  ...
  [157 156 158]
  [158 158 158]
  [158 158 158]]

 ...

 [[147 147 147]
  [146 146 146]
  [146 146 146]
  ..

[[[155 152 153]
  [152 149 150]
  [148 145 146]
  ...
  [191 187 190]
  [190 190 190]
  [189 189 189]]

 [[155 152 153]
  [152 149 150]
  [147 144 145]
  ...
  [177 173 176]
  [175 175 175]
  [176 176 176]]

 [[154 151 152]
  [152 149 150]
  [147 144 145]
  ...
  [158 157 159]
  [159 159 159]
  [160 160 160]]

 ...

 [[147 147 147]
  [147 147 147]
  [145 145 145]
  ...
  [105 103 108]
  [ 91  95  97]
  [ 86  90  92]]

 [[147 147 147]
  [147 147 147]
  [146 146 146]
  ...
  [109 108 110]
  [ 98  97  99]
  [ 95  94  96]]

 [[146 146 146]
  [146 146 146]
  [146 146 146]
  ...
  [110 109 111]
  [101 100 102]
  [ 95  94  96]]]
[[[153 153 153]
  [150 150 150]
  [146 146 146]
  ...
  [190 186 189]
  [189 189 189]
  [189 189 189]]

 [[153 153 153]
  [150 150 150]
  [145 145 145]
  ...
  [181 177 180]
  [181 181 181]
  [181 181 181]]

 [[152 152 152]
  [150 150 150]
  [145 145 145]
  ...
  [157 156 158]
  [159 159 159]
  [161 161 161]]

 ...

 [[147 147 147]
  [147 147 147]
  [145 145 145]
  ..

[[[153 149 152]
  [153 149 152]
  [148 144 147]
  ...
  [190 190 190]
  [190 190 190]
  [188 188 188]]

 [[153 149 152]
  [153 149 152]
  [148 144 147]
  ...
  [181 181 181]
  [181 181 181]
  [179 179 179]]

 [[154 150 153]
  [153 149 152]
  [148 144 147]
  ...
  [158 158 158]
  [157 157 157]
  [159 159 159]]

 ...

 [[147 147 147]
  [146 146 146]
  [145 145 145]
  ...
  [111 109 114]
  [ 91  95  97]
  [ 85  89  91]]

 [[147 147 147]
  [146 146 146]
  [146 146 146]
  ...
  [112 114 116]
  [ 97  99 101]
  [ 90  92  94]]

 [[146 146 146]
  [145 145 145]
  [145 145 145]
  ...
  [109 111 113]
  [100 102 104]
  [ 92  94  96]]]
[[[154 151 152]
  [153 150 151]
  [148 145 146]
  ...
  [190 190 190]
  [189 189 189]
  [187 187 187]]

 [[154 151 152]
  [153 150 151]
  [148 145 146]
  ...
  [180 180 180]
  [180 180 180]
  [179 179 179]]

 [[155 152 153]
  [153 150 151]
  [148 145 146]
  ...
  [159 159 159]
  [158 158 158]
  [159 159 159]]

 ...

 [[147 147 147]
  [147 147 147]
  [145 145 145]
  ..

[[[154 154 154]
  [152 152 152]
  [147 147 147]
  ...
  [188 188 188]
  [188 188 188]
  [190 190 190]]

 [[153 153 153]
  [151 151 151]
  [146 146 146]
  ...
  [180 180 180]
  [183 183 183]
  [185 185 185]]

 [[153 153 153]
  [151 151 151]
  [146 146 146]
  ...
  [159 156 157]
  [159 159 159]
  [158 158 158]]

 ...

 [[146 146 146]
  [146 146 146]
  [146 146 146]
  ...
  [104 107 112]
  [ 96 100 102]
  [ 90  94  96]]

 [[146 146 146]
  [146 146 146]
  [146 146 146]
  ...
  [105 108 113]
  [ 96 100 102]
  [ 90  94  96]]

 [[145 145 145]
  [146 146 146]
  [146 146 146]
  ...
  [103 106 111]
  [ 96 100 102]
  [ 90  94  96]]]
[[[153 153 153]
  [150 150 150]
  [145 145 145]
  ...
  [189 189 189]
  [188 188 188]
  [190 190 190]]

 [[153 153 153]
  [150 150 150]
  [145 145 145]
  ...
  [181 181 181]
  [183 183 183]
  [185 185 185]]

 [[153 153 153]
  [150 150 150]
  [145 145 145]
  ...
  [159 156 157]
  [159 159 159]
  [158 158 158]]

 ...

 [[146 146 146]
  [146 146 146]
  [146 146 146]
  ..

[[[153 150 151]
  [151 148 149]
  [148 145 146]
  ...
  [190 190 190]
  [192 192 192]
  [193 193 193]]

 [[154 151 152]
  [153 150 151]
  [146 143 144]
  ...
  [174 174 174]
  [172 172 172]
  [171 171 171]]

 [[154 151 152]
  [153 150 151]
  [148 145 146]
  ...
  [158 158 158]
  [157 157 157]
  [158 158 158]]

 ...

 [[146 146 146]
  [145 145 145]
  [146 146 146]
  ...
  [114 116 118]
  [100 104 106]
  [ 90  94  96]]

 [[147 147 147]
  [146 146 146]
  [145 145 145]
  ...
  [113 115 117]
  [103 107 109]
  [ 91  95  97]]

 [[146 146 146]
  [145 145 145]
  [144 144 144]
  ...
  [108 110 112]
  [102 106 108]
  [ 95  99 101]]]
[[[153 150 151]
  [152 149 150]
  [148 145 146]
  ...
  [187 187 187]
  [188 188 188]
  [189 189 189]]

 [[154 151 152]
  [153 150 151]
  [147 144 145]
  ...
  [166 166 166]
  [166 166 166]
  [165 165 165]]

 [[154 151 152]
  [154 151 152]
  [149 146 147]
  ...
  [160 160 160]
  [163 163 163]
  [163 163 163]]

 ...

 [[146 146 146]
  [145 145 145]
  [146 146 146]
  ..

[[[154 154 154]
  [152 152 152]
  [149 149 149]
  ...
  [180 182 184]
  [186 186 186]
  [187 187 187]]

 [[154 154 154]
  [153 153 153]
  [150 150 150]
  ...
  [158 160 162]
  [161 161 161]
  [158 158 158]]

 [[153 153 153]
  [152 152 152]
  [150 150 150]
  ...
  [158 160 162]
  [163 163 163]
  [164 164 164]]

 ...

 [[147 147 147]
  [147 147 147]
  [146 146 146]
  ...
  [114 119 119]
  [104 108 110]
  [ 96 100 102]]

 [[147 147 147]
  [147 147 147]
  [147 147 147]
  ...
  [110 114 116]
  [102 106 108]
  [ 96 100 102]]

 [[147 147 147]
  [147 147 147]
  [145 145 145]
  ...
  [103 107 109]
  [ 99 103 105]
  [ 98 102 104]]]
the detection is [[[[0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0.

[[[155 152 153]
  [155 152 153]
  [152 149 150]
  ...
  [171 173 175]
  [175 175 175]
  [173 173 173]]

 [[155 152 153]
  [155 152 153]
  [152 149 150]
  ...
  [153 155 157]
  [156 156 156]
  [157 157 157]]

 [[154 151 152]
  [154 151 152]
  [152 149 150]
  ...
  [171 173 175]
  [174 174 174]
  [174 174 174]]

 ...

 [[147 146 148]
  [147 146 148]
  [146 145 147]
  ...
  [119 124 124]
  [109 113 115]
  [ 99 103 105]]

 [[147 146 148]
  [147 146 148]
  [146 145 147]
  ...
  [114 118 120]
  [106 110 112]
  [ 99 103 105]]

 [[147 146 148]
  [147 146 148]
  [145 144 146]
  ...
  [107 111 113]
  [103 107 109]
  [100 104 106]]]
[[[156 153 154]
  [156 153 154]
  [152 149 150]
  ...
  [171 173 175]
  [175 175 175]
  [173 173 173]]

 [[156 153 154]
  [156 153 154]
  [152 149 150]
  ...
  [153 155 157]
  [156 156 156]
  [157 157 157]]

 [[156 153 154]
  [155 152 153]
  [152 149 150]
  ...
  [171 173 175]
  [174 174 174]
  [172 172 172]]

 ...

 [[147 146 148]
  [146 145 147]
  [146 145 147]
  ..

[[[155 152 153]
  [155 152 153]
  [153 150 151]
  ...
  [174 173 175]
  [175 175 175]
  [175 175 175]]

 [[156 153 154]
  [156 153 154]
  [153 150 151]
  ...
  [154 153 155]
  [157 157 157]
  [156 156 156]]

 [[156 153 154]
  [156 153 154]
  [152 149 150]
  ...
  [171 170 172]
  [172 172 172]
  [172 172 172]]

 ...

 [[147 147 147]
  [147 147 147]
  [146 146 146]
  ...
  [117 122 122]
  [106 110 112]
  [100 104 106]]

 [[146 146 146]
  [145 145 145]
  [146 146 146]
  ...
  [111 115 117]
  [102 106 108]
  [ 98 102 104]]

 [[147 147 147]
  [144 144 144]
  [144 144 144]
  ...
  [105 109 111]
  [ 99 103 105]
  [100 104 106]]]
[[[156 153 154]
  [156 153 154]
  [154 151 152]
  ...
  [171 170 172]
  [170 170 170]
  [170 170 170]]

 [[158 155 156]
  [158 155 156]
  [154 151 152]
  ...
  [157 156 158]
  [158 158 158]
  [158 158 158]]

 [[158 155 156]
  [158 155 156]
  [153 150 151]
  ...
  [178 177 179]
  [178 178 178]
  [179 179 179]]

 ...

 [[147 147 147]
  [147 147 147]
  [146 146 146]
  ..

[[[156 153 154]
  [156 153 154]
  [154 151 152]
  ...
  [163 165 167]
  [168 168 168]
  [168 168 168]]

 [[156 153 154]
  [156 153 154]
  [154 151 152]
  ...
  [155 157 159]
  [158 158 158]
  [157 157 157]]

 [[156 153 154]
  [156 153 154]
  [154 151 152]
  ...
  [178 180 182]
  [179 179 179]
  [181 181 181]]

 ...

 [[149 146 147]
  [149 146 147]
  [146 146 146]
  ...
  [116 121 121]
  [107 111 113]
  [ 99 103 105]]

 [[149 146 147]
  [147 144 145]
  [145 145 145]
  ...
  [111 115 117]
  [106 110 112]
  [100 104 106]]

 [[151 148 149]
  [148 145 146]
  [146 146 146]
  ...
  [109 113 115]
  [104 108 110]
  [100 104 106]]]
[[[158 155 156]
  [158 155 156]
  [154 151 152]
  ...
  [164 166 168]
  [168 168 168]
  [168 168 168]]

 [[156 153 154]
  [156 153 154]
  [154 151 152]
  ...
  [155 157 159]
  [158 158 158]
  [159 159 159]]

 [[156 153 154]
  [156 153 154]
  [154 151 152]
  ...
  [178 180 182]
  [181 181 181]
  [181 181 181]]

 ...

 [[149 146 147]
  [149 146 147]
  [145 145 145]
  ..

[[[154 151 152]
  [155 152 153]
  [152 149 150]
  ...
  [171 174 174]
  [176 176 176]
  [175 175 175]]

 [[155 152 153]
  [155 152 153]
  [153 150 151]
  ...
  [151 154 154]
  [157 157 157]
  [154 154 154]]

 [[155 152 153]
  [154 151 152]
  [153 150 151]
  ...
  [170 173 173]
  [174 174 174]
  [175 175 175]]

 ...

 [[149 146 147]
  [149 146 147]
  [146 146 146]
  ...
  [111 116 116]
  [105 109 111]
  [ 98 102 104]]

 [[148 145 146]
  [148 145 146]
  [146 146 146]
  ...
  [107 111 113]
  [103 107 109]
  [ 98 102 104]]

 [[151 148 149]
  [149 146 147]
  [145 145 145]
  ...
  [105 109 111]
  [100 104 106]
  [ 99 103 105]]]
[[[154 151 152]
  [155 152 153]
  [152 149 150]
  ...
  [173 176 176]
  [178 178 178]
  [174 174 174]]

 [[155 152 153]
  [155 152 153]
  [153 150 151]
  ...
  [153 156 156]
  [156 156 156]
  [152 152 152]]

 [[155 152 153]
  [154 151 152]
  [153 150 151]
  ...
  [169 172 172]
  [173 173 173]
  [174 174 174]]

 ...

 [[149 146 147]
  [149 146 147]
  [146 146 146]
  ..

the detection is [[[[ 0.         15.          0.9799095   0.57442456  0.61055094
     0.75775176  1.0056727 ]
   [ 0.         15.          0.27253854  0.6823604   0.6442021
     0.92942226  1.01014   ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.  

[[[154 154 154]
  [154 154 154]
  [151 151 151]
  ...
  [158 160 162]
  [163 163 163]
  [161 161 161]]

 [[154 154 154]
  [154 154 154]
  [150 150 150]
  ...
  [155 157 159]
  [159 159 159]
  [161 161 161]]

 [[154 154 154]
  [154 154 154]
  [152 152 152]
  ...
  [182 184 186]
  [183 183 183]
  [185 185 185]]

 ...

 [[148 145 146]
  [149 146 147]
  [149 146 147]
  ...
  [116 118 120]
  [105 109 111]
  [ 98 102 104]]

 [[147 144 145]
  [148 145 146]
  [146 143 144]
  ...
  [109 113 115]
  [105 109 111]
  [ 98 102 104]]

 [[148 145 146]
  [149 146 147]
  [147 144 145]
  ...
  [107 111 113]
  [100 104 106]
  [ 97 101 103]]]
[[[154 154 154]
  [153 153 153]
  [152 152 152]
  ...
  [158 160 162]
  [163 163 163]
  [161 161 161]]

 [[156 156 156]
  [154 154 154]
  [152 152 152]
  ...
  [155 157 159]
  [159 159 159]
  [161 161 161]]

 [[157 157 157]
  [154 154 154]
  [152 152 152]
  ...
  [182 184 186]
  [183 183 183]
  [185 185 185]]

 ...

 [[148 145 146]
  [148 145 146]
  [147 144 145]
  ..

[[[153 153 153]
  [153 153 153]
  [152 152 152]
  ...
  [158 158 158]
  [159 159 159]
  [159 159 159]]

 [[153 153 153]
  [153 153 153]
  [152 152 152]
  ...
  [163 163 163]
  [165 165 165]
  [165 165 165]]

 [[153 153 153]
  [153 153 153]
  [154 154 154]
  ...
  [188 188 188]
  [190 190 190]
  [192 192 192]]

 ...

 [[148 145 146]
  [147 144 145]
  [146 143 144]
  ...
  [123 122 124]
  [112 114 116]
  [100 102 104]]

 [[149 146 147]
  [148 145 146]
  [145 142 143]
  ...
  [114 116 118]
  [109 111 113]
  [ 99 101 103]]

 [[151 148 149]
  [149 146 147]
  [146 143 144]
  ...
  [111 113 115]
  [105 107 109]
  [ 98 100 102]]]
[[[153 150 151]
  [155 152 153]
  [154 151 152]
  ...
  [158 158 158]
  [159 159 159]
  [159 159 159]]

 [[153 150 151]
  [155 152 153]
  [154 151 152]
  ...
  [170 170 170]
  [172 172 172]
  [172 172 172]]

 [[154 151 152]
  [155 152 153]
  [156 153 154]
  ...
  [192 192 192]
  [193 193 193]
  [194 194 194]]

 ...

 [[148 145 146]
  [148 145 146]
  [147 144 145]
  ..

[[[153 150 151]
  [152 149 150]
  [149 146 147]
  ...
  [154 154 154]
  [154 154 154]
  [154 154 154]]

 [[153 150 151]
  [153 150 151]
  [151 148 149]
  ...
  [167 167 167]
  [167 167 167]
  [168 168 168]]

 [[153 150 151]
  [153 150 151]
  [151 148 149]
  ...
  [190 190 190]
  [192 192 192]
  [192 192 192]]

 ...

 [[146 146 146]
  [147 147 147]
  [145 145 145]
  ...
  [124 124 124]
  [108 111 111]
  [ 97 100 100]]

 [[146 146 146]
  [147 147 147]
  [145 145 145]
  ...
  [119 119 119]
  [105 108 108]
  [ 97 100 100]]

 [[147 147 147]
  [146 146 146]
  [146 146 146]
  ...
  [116 116 116]
  [101 104 104]
  [ 93  96  96]]]
[[[152 149 150]
  [152 149 150]
  [149 146 147]
  ...
  [157 157 157]
  [157 157 157]
  [157 157 157]]

 [[152 149 150]
  [152 149 150]
  [149 146 147]
  ...
  [174 174 174]
  [174 174 174]
  [175 175 175]]

 [[152 149 150]
  [152 149 150]
  [149 146 147]
  ...
  [194 194 194]
  [193 193 193]
  [194 194 194]]

 ...

 [[149 146 147]
  [149 146 147]
  [147 144 145]
  ..

[[[146 143 144]
  [147 144 145]
  [148 145 146]
  ...
  [158 161 161]
  [163 163 163]
  [163 163 163]]

 [[147 144 145]
  [148 145 146]
  [149 146 147]
  ...
  [185 188 188]
  [188 188 188]
  [187 187 187]]

 [[148 145 146]
  [147 144 145]
  [147 144 145]
  ...
  [191 194 194]
  [194 194 194]
  [194 194 194]]

 ...

 [[148 145 146]
  [147 144 145]
  [147 144 145]
  ...
  [118 121 121]
  [111 114 114]
  [104 107 107]]

 [[148 145 146]
  [148 145 146]
  [148 145 146]
  ...
  [111 116 116]
  [107 110 110]
  [100 103 103]]

 [[149 146 147]
  [151 148 149]
  [151 148 149]
  ...
  [106 111 111]
  [101 104 104]
  [ 98 101 101]]]
[[[148 145 146]
  [148 145 146]
  [147 144 145]
  ...
  [157 159 161]
  [163 163 163]
  [163 163 163]]

 [[148 145 146]
  [149 146 147]
  [148 145 146]
  ...
  [186 188 190]
  [188 188 188]
  [187 187 187]]

 [[148 145 146]
  [147 144 145]
  [147 144 145]
  ...
  [192 194 196]
  [194 194 194]
  [194 194 194]]

 ...

 [[148 145 146]
  [147 144 145]
  [147 144 145]
  ..

[[[146 143 144]
  [146 143 144]
  [144 141 142]
  ...
  [154 156 158]
  [158 158 158]
  [160 160 160]]

 [[146 143 144]
  [147 144 145]
  [145 142 143]
  ...
  [182 184 186]
  [183 183 183]
  [183 183 183]]

 [[147 144 145]
  [147 144 145]
  [145 142 143]
  ...
  [191 193 195]
  [193 193 193]
  [193 193 193]]

 ...

 [[149 146 147]
  [148 145 146]
  [147 144 145]
  ...
  [119 122 122]
  [113 116 116]
  [106 109 109]]

 [[149 146 147]
  [148 145 146]
  [147 144 145]
  ...
  [112 117 117]
  [109 112 112]
  [106 109 109]]

 [[147 144 145]
  [149 146 147]
  [149 146 147]
  ...
  [106 111 111]
  [107 110 110]
  [102 105 105]]]
[[[145 142 143]
  [145 142 143]
  [142 139 140]
  ...
  [153 155 157]
  [157 157 157]
  [159 159 159]]

 [[145 142 143]
  [146 143 144]
  [144 141 142]
  ...
  [175 177 179]
  [176 176 176]
  [178 178 178]]

 [[146 143 144]
  [146 143 144]
  [144 141 142]
  ...
  [193 195 197]
  [193 193 193]
  [193 193 193]]

 ...

 [[149 146 147]
  [148 145 146]
  [147 144 145]
  ..

[[[147 144 145]
  [147 144 145]
  [146 143 144]
  ...
  [158 157 159]
  [160 160 160]
  [160 160 160]]

 [[147 144 145]
  [147 144 145]
  [146 143 144]
  ...
  [186 185 187]
  [186 186 186]
  [188 188 188]]

 [[147 144 145]
  [148 145 146]
  [148 145 146]
  ...
  [189 188 190]
  [190 190 190]
  [190 190 190]]

 ...

 [[144 143 145]
  [144 143 145]
  [144 143 145]
  ...
  [119 121 123]
  [115 118 118]
  [106 109 109]]

 [[145 144 146]
  [145 144 146]
  [145 144 146]
  ...
  [116 120 122]
  [113 116 116]
  [107 110 110]]

 [[143 142 144]
  [144 143 145]
  [144 143 145]
  ...
  [111 115 117]
  [108 111 111]
  [106 109 109]]]
[[[148 145 146]
  [148 145 146]
  [147 144 145]
  ...
  [158 157 159]
  [160 160 160]
  [160 160 160]]

 [[147 144 145]
  [147 144 145]
  [146 143 144]
  ...
  [186 185 187]
  [186 186 186]
  [188 188 188]]

 [[146 143 144]
  [147 144 145]
  [147 144 145]
  ...
  [189 188 190]
  [190 190 190]
  [190 190 190]]

 ...

 [[144 143 145]
  [144 143 145]
  [144 143 145]
  ..

[[[152 148 151]
  [153 149 152]
  [153 149 152]
  ...
  [158 157 159]
  [158 158 158]
  [159 159 159]]

 [[152 148 151]
  [153 149 152]
  [153 149 152]
  ...
  [188 187 189]
  [188 188 188]
  [187 187 187]]

 [[151 147 150]
  [153 149 152]
  [154 150 153]
  ...
  [192 191 193]
  [193 193 193]
  [193 193 193]]

 ...

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ...
  [118 122 124]
  [113 118 118]
  [105 110 110]]

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ...
  [115 117 119]
  [106 111 111]
  [103 108 108]]

 [[145 145 145]
  [146 146 146]
  [146 146 146]
  ...
  [106 108 110]
  [102 107 107]
  [ 99 104 104]]]
the detection is [[[[0.0000000e+00 1.5000000e+01 4.2547488e-01 2.6622403e-01
    7.1376562e-06 4.7133541e-01 3.0218440e-01]
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
    0.0000000e+00 0.0000000e+00 0.0000000e+00]
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
    0.0000000e+00 0.0000000e+00 0.0000000e+00]
   [0.0000000e+00 0.0000000e+00 

[[[152 148 151]
  [154 150 153]
  [154 150 153]
  ...
  [157 156 158]
  [158 158 158]
  [157 157 157]]

 [[151 147 150]
  [153 149 152]
  [153 149 152]
  ...
  [187 186 188]
  [188 188 188]
  [187 187 187]]

 [[152 148 151]
  [155 151 154]
  [155 151 154]
  ...
  [192 191 193]
  [193 193 193]
  [194 194 194]]

 ...

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ...
  [117 121 123]
  [113 118 118]
  [105 110 110]]

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ...
  [115 117 119]
  [106 111 111]
  [103 108 108]]

 [[145 145 145]
  [146 146 146]
  [146 146 146]
  ...
  [108 110 112]
  [102 107 107]
  [ 99 104 104]]]
[[[153 149 152]
  [153 149 152]
  [153 149 152]
  ...
  [157 156 158]
  [158 158 158]
  [157 157 157]]

 [[151 147 150]
  [153 149 152]
  [153 149 152]
  ...
  [187 186 188]
  [188 188 188]
  [187 187 187]]

 [[152 148 151]
  [155 151 154]
  [155 151 154]
  ...
  [192 191 193]
  [193 193 193]
  [194 194 194]]

 ...

 [[147 144 145]
  [145 142 143]
  [145 142 143]
  ..

[[[150 150 150]
  [151 151 151]
  [151 151 151]
  ...
  [174 174 174]
  [174 174 174]
  [173 173 173]]

 [[150 150 150]
  [151 151 151]
  [151 151 151]
  ...
  [189 189 189]
  [189 189 189]
  [189 189 189]]

 [[150 150 150]
  [150 150 150]
  [151 151 151]
  ...
  [188 188 188]
  [187 187 187]
  [189 189 189]]

 ...

 [[143 143 143]
  [144 144 144]
  [145 145 145]
  ...
  [123 122 124]
  [116 119 119]
  [109 112 112]]

 [[140 140 140]
  [143 143 143]
  [146 146 146]
  ...
  [121 117 120]
  [113 116 116]
  [107 110 110]]

 [[137 137 137]
  [139 139 139]
  [144 144 144]
  ...
  [114 110 113]
  [108 111 111]
  [107 110 110]]]
[[[149 149 149]
  [152 152 152]
  [154 154 154]
  ...
  [173 173 173]
  [174 174 174]
  [173 173 173]]

 [[149 149 149]
  [152 152 152]
  [153 153 153]
  ...
  [190 190 190]
  [189 189 189]
  [189 189 189]]

 [[149 149 149]
  [152 152 152]
  [156 156 156]
  ...
  [188 188 188]
  [187 187 187]
  [189 189 189]]

 ...

 [[145 145 145]
  [145 145 145]
  [145 145 145]
  ..

the detection is [[[[ 0.         15.          0.9460739   0.31409734  0.32832873
     0.49030322  0.6800852 ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.          0.          0.
     0.          0.        ]
   [ 0.          0.          0.         

[[[154 150 153]
  [154 150 153]
  [155 151 154]
  ...
  [170 170 170]
  [170 170 170]
  [171 171 171]]

 [[152 148 151]
  [153 149 152]
  [154 150 153]
  ...
  [195 195 195]
  [192 192 192]
  [190 190 190]]

 [[153 149 152]
  [154 150 153]
  [154 150 153]
  ...
  [193 193 193]
  [192 192 192]
  [193 193 193]]

 ...

 [[145 144 146]
  [144 143 145]
  [143 142 144]
  ...
  [119 118 120]
  [114 117 117]
  [109 112 112]]

 [[143 142 144]
  [143 142 144]
  [142 141 143]
  ...
  [119 114 120]
  [112 115 115]
  [106 109 109]]

 [[140 139 141]
  [143 142 144]
  [143 142 144]
  ...
  [117 112 118]
  [107 110 110]
  [104 107 107]]]
[[[154 150 153]
  [154 150 153]
  [155 151 154]
  ...
  [175 175 175]
  [176 176 176]
  [175 175 175]]

 [[154 150 153]
  [155 151 154]
  [156 152 155]
  ...
  [196 196 196]
  [194 194 194]
  [194 194 194]]

 [[155 151 154]
  [156 152 155]
  [156 152 155]
  ...
  [192 192 192]
  [192 192 192]
  [193 193 193]]

 ...

 [[145 144 146]
  [144 143 145]
  [143 142 144]
  ..

[[[152 149 150]
  [155 152 153]
  [158 155 156]
  ...
  [180 176 179]
  [180 180 180]
  [179 179 179]]

 [[153 150 151]
  [154 151 152]
  [156 153 154]
  ...
  [197 193 196]
  [196 196 196]
  [195 195 195]]

 [[154 151 152]
  [155 152 153]
  [158 155 156]
  ...
  [192 188 191]
  [190 190 190]
  [189 189 189]]

 ...

 [[148 144 147]
  [148 144 147]
  [146 142 145]
  ...
  [119 120 125]
  [115 118 118]
  [109 112 112]]

 [[148 144 147]
  [148 144 147]
  [146 142 145]
  ...
  [119 121 123]
  [112 115 115]
  [106 109 109]]

 [[142 138 141]
  [144 140 143]
  [146 142 145]
  ...
  [112 114 116]
  [107 110 110]
  [105 108 108]]]
[[[153 150 151]
  [156 153 154]
  [158 155 156]
  ...
  [178 174 177]
  [179 179 179]
  [180 180 180]]

 [[152 149 150]
  [154 151 152]
  [155 152 153]
  ...
  [198 194 197]
  [196 196 196]
  [193 193 193]]

 [[153 150 151]
  [155 152 153]
  [156 153 154]
  ...
  [192 188 191]
  [189 189 189]
  [189 189 189]]

 ...

 [[148 144 147]
  [148 144 147]
  [146 142 145]
  ..

[[[154 150 153]
  [156 152 155]
  [156 152 155]
  ...
  [176 172 175]
  [176 176 176]
  [173 173 173]]

 [[154 150 153]
  [156 152 155]
  [156 152 155]
  ...
  [197 193 196]
  [194 194 194]
  [192 192 192]]

 [[154 150 153]
  [155 151 154]
  [155 151 154]
  ...
  [195 191 194]
  [194 194 194]
  [193 193 193]]

 ...

 [[147 143 146]
  [147 143 146]
  [145 141 144]
  ...
  [119 120 125]
  [116 119 119]
  [108 111 111]]

 [[147 143 146]
  [146 142 145]
  [146 142 145]
  ...
  [116 118 120]
  [112 115 115]
  [107 110 110]]

 [[142 138 141]
  [145 141 144]
  [142 138 141]
  ...
  [111 113 115]
  [108 111 111]
  [105 108 108]]]
[[[154 150 153]
  [156 152 155]
  [156 152 155]
  ...
  [182 178 181]
  [181 181 181]
  [178 178 178]]

 [[154 150 153]
  [156 152 155]
  [156 152 155]
  ...
  [201 197 200]
  [195 195 195]
  [194 194 194]]

 [[154 150 153]
  [155 151 154]
  [155 151 154]
  ...
  [194 190 193]
  [194 194 194]
  [193 193 193]]

 ...

 [[146 145 147]
  [146 145 147]
  [145 144 146]
  ..

[[[155 151 154]
  [154 150 153]
  [155 151 154]
  ...
  [185 184 186]
  [185 185 185]
  [183 183 183]]

 [[155 151 154]
  [154 150 153]
  [154 150 153]
  ...
  [196 195 197]
  [195 195 195]
  [196 196 196]]

 [[153 149 152]
  [155 151 154]
  [156 152 155]
  ...
  [192 191 193]
  [190 190 190]
  [190 190 190]]

 ...

 [[145 145 145]
  [146 146 146]
  [145 145 145]
  ...
  [116 117 122]
  [113 116 116]
  [108 111 111]]

 [[146 146 146]
  [146 146 146]
  [146 146 146]
  ...
  [113 115 117]
  [112 115 115]
  [108 111 111]]

 [[142 142 142]
  [142 142 142]
  [145 145 145]
  ...
  [107 109 111]
  [107 110 110]
  [105 108 108]]]
[[[151 150 152]
  [152 151 153]
  [154 153 155]
  ...
  [181 180 182]
  [185 185 185]
  [183 183 183]]

 [[152 151 153]
  [152 151 153]
  [153 152 154]
  ...
  [194 193 195]
  [195 195 195]
  [196 196 196]]

 [[151 150 152]
  [153 152 154]
  [154 153 155]
  ...
  [190 189 191]
  [190 190 190]
  [190 190 190]]

 ...

 [[146 146 146]
  [146 146 146]
  [145 145 145]
  ..

[[[151 151 151]
  [153 153 153]
  [153 153 153]
  ...
  [170 169 171]
  [168 168 168]
  [168 168 168]]

 [[151 151 151]
  [153 153 153]
  [153 153 153]
  ...
  [193 192 194]
  [193 193 193]
  [193 193 193]]

 [[151 151 151]
  [153 153 153]
  [153 153 153]
  ...
  [193 192 194]
  [194 194 194]
  [195 195 195]]

 ...

 [[145 145 145]
  [146 146 146]
  [147 147 147]
  ...
  [124 123 125]
  [116 121 121]
  [107 112 112]]

 [[145 145 145]
  [146 146 146]
  [145 145 145]
  ...
  [118 120 122]
  [114 119 119]
  [107 112 112]]

 [[140 140 140]
  [145 145 145]
  [146 146 146]
  ...
  [111 113 115]
  [106 111 111]
  [102 107 107]]]
[[[152 152 152]
  [154 154 154]
  [154 154 154]
  ...
  [168 167 169]
  [168 168 168]
  [168 168 168]]

 [[153 153 153]
  [156 156 156]
  [156 156 156]
  ...
  [194 193 195]
  [193 193 193]
  [193 193 193]]

 [[153 153 153]
  [156 156 156]
  [156 156 156]
  ...
  [194 193 195]
  [194 194 194]
  [195 195 195]]

 ...

 [[145 145 145]
  [146 146 146]
  [147 147 147]
  ..

[[[155 152 153]
  [155 152 153]
  [155 152 153]
  ...
  [163 163 163]
  [164 164 164]
  [164 164 164]]

 [[155 152 153]
  [155 152 153]
  [156 153 154]
  ...
  [187 187 187]
  [187 187 187]
  [187 187 187]]

 [[153 150 151]
  [154 151 152]
  [155 152 153]
  ...
  [193 193 193]
  [194 194 194]
  [194 194 194]]

 ...

 [[151 148 149]
  [151 148 149]
  [149 146 147]
  ...
  [114 117 117]
  [112 117 117]
  [106 111 111]]

 [[147 144 145]
  [147 144 145]
  [147 144 145]
  ...
  [112 117 117]
  [111 116 116]
  [106 111 111]]

 [[146 143 144]
  [146 143 144]
  [148 145 146]
  ...
  [111 116 116]
  [109 114 114]
  [105 110 110]]]
[[[154 151 152]
  [156 153 154]
  [156 153 154]
  ...
  [159 158 160]
  [160 160 160]
  [160 160 160]]

 [[153 150 151]
  [155 152 153]
  [156 153 154]
  ...
  [185 184 186]
  [185 185 185]
  [185 185 185]]

 [[152 149 150]
  [154 151 152]
  [156 153 154]
  ...
  [195 194 196]
  [194 194 194]
  [195 195 195]]

 ...

 [[151 148 149]
  [149 146 147]
  [149 146 147]
  ..

[[[154 151 152]
  [155 152 153]
  [153 150 151]
  ...
  [160 160 160]
  [158 158 158]
  [157 157 157]]

 [[154 151 152]
  [156 153 154]
  [154 151 152]
  ...
  [167 167 167]
  [167 167 167]
  [167 167 167]]

 [[153 150 151]
  [156 153 154]
  [156 153 154]
  ...
  [189 189 189]
  [190 190 190]
  [189 189 189]]

 ...

 [[149 146 145]
  [151 148 147]
  [148 145 146]
  ...
  [114 117 117]
  [106 111 111]
  [100 105 105]]

 [[149 146 145]
  [148 145 144]
  [148 145 146]
  ...
  [112 115 115]
  [105 110 110]
  [102 107 107]]

 [[149 146 145]
  [149 146 145]
  [148 145 146]
  ...
  [112 115 115]
  [106 111 111]
  [102 107 107]]]
the detection is [[[[0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0.

[[[155 152 153]
  [156 153 154]
  [158 155 156]
  ...
  [186 186 186]
  [190 190 190]
  [192 192 192]]

 [[155 152 153]
  [156 153 154]
  [156 153 154]
  ...
  [196 196 196]
  [196 196 196]
  [196 196 196]]

 [[154 151 152]
  [154 151 152]
  [155 152 153]
  ...
  [189 189 189]
  [189 189 189]
  [190 190 190]]

 ...

 [[149 146 145]
  [149 146 145]
  [149 146 147]
  ...
  [119 122 122]
  [112 117 117]
  [106 111 111]]

 [[147 144 143]
  [148 145 144]
  [149 146 147]
  ...
  [113 116 116]
  [107 112 112]
  [104 109 109]]

 [[140 137 136]
  [145 142 141]
  [151 148 149]
  ...
  [109 112 112]
  [103 108 108]
  [100 105 105]]]
[[[155 151 154]
  [156 152 155]
  [158 154 157]
  ...
  [181 181 181]
  [183 183 183]
  [186 186 186]]

 [[155 151 154]
  [156 152 155]
  [158 154 157]
  ...
  [197 197 197]
  [196 196 196]
  [197 197 197]]

 [[154 150 153]
  [155 151 154]
  [155 151 154]
  ...
  [190 190 190]
  [192 192 192]
  [194 194 194]]

 ...

 [[149 146 145]
  [148 145 144]
  [148 145 146]
  ..

[[[152 152 152]
  [153 153 153]
  [154 154 154]
  ...
  [170 170 170]
  [167 167 167]
  [170 170 170]]

 [[152 152 152]
  [153 153 153]
  [154 154 154]
  ...
  [194 194 194]
  [195 195 195]
  [194 194 194]]

 [[152 152 152]
  [153 153 153]
  [156 156 156]
  ...
  [194 194 194]
  [195 195 195]
  [194 194 194]]

 ...

 [[147 147 147]
  [146 146 146]
  [148 145 146]
  ...
  [119 121 123]
  [112 117 117]
  [104 109 109]]

 [[149 149 149]
  [147 147 147]
  [147 144 145]
  ...
  [116 118 120]
  [107 112 112]
  [102 107 107]]

 [[145 145 145]
  [146 146 146]
  [149 146 147]
  ...
  [113 115 117]
  [103 108 108]
  [ 98 103 103]]]
[[[151 151 151]
  [153 153 153]
  [154 154 154]
  ...
  [163 163 163]
  [164 164 164]
  [164 164 164]]

 [[151 151 151]
  [153 153 153]
  [154 154 154]
  ...
  [187 187 187]
  [188 188 188]
  [186 186 186]]

 [[152 152 152]
  [154 154 154]
  [154 154 154]
  ...
  [196 196 196]
  [197 197 197]
  [199 199 199]]

 ...

 [[147 147 147]
  [145 145 145]
  [147 144 145]
  ..

[[[154 154 154]
  [154 154 154]
  [152 152 152]
  ...
  [163 166 166]
  [170 170 170]
  [173 173 173]]

 [[154 154 154]
  [154 154 154]
  [152 152 152]
  ...
  [187 190 190]
  [195 195 195]
  [195 195 195]]

 [[156 156 156]
  [156 156 156]
  [151 151 151]
  ...
  [190 193 193]
  [193 193 193]
  [194 194 194]]

 ...

 [[149 149 149]
  [147 147 147]
  [147 144 145]
  ...
  [125 128 128]
  [112 117 117]
  [102 107 107]]

 [[149 149 149]
  [149 149 149]
  [148 145 146]
  ...
  [119 122 122]
  [109 114 114]
  [ 98 103 103]]

 [[145 145 145]
  [147 147 147]
  [149 146 147]
  ...
  [111 114 114]
  [104 109 109]
  [ 97 102 102]]]
[[[156 156 156]
  [156 156 156]
  [152 152 152]
  ...
  [167 170 170]
  [176 176 176]
  [179 179 179]]

 [[156 156 156]
  [156 156 156]
  [153 153 153]
  ...
  [190 193 193]
  [196 196 196]
  [196 196 196]]

 [[157 157 157]
  [156 156 156]
  [152 152 152]
  ...
  [189 192 192]
  [192 192 192]
  [193 193 193]]

 ...

 [[149 149 149]
  [147 147 147]
  [147 144 145]
  ..

[[[154 151 152]
  [155 152 153]
  [152 149 150]
  ...
  [177 179 181]
  [179 179 179]
  [181 181 181]]

 [[155 152 153]
  [155 152 153]
  [152 149 150]
  ...
  [189 191 193]
  [194 194 194]
  [195 195 195]]

 [[155 152 153]
  [155 152 153]
  [154 151 152]
  ...
  [186 188 190]
  [190 190 190]
  [190 190 190]]

 ...

 [[149 149 149]
  [146 146 146]
  [145 145 145]
  ...
  [116 118 120]
  [115 115 115]
  [109 109 109]]

 [[149 149 149]
  [147 147 147]
  [146 146 146]
  ...
  [115 114 116]
  [109 109 109]
  [103 103 103]]

 [[147 147 147]
  [147 147 147]
  [147 147 147]
  ...
  [110 109 111]
  [104 104 104]
  [101 101 101]]]
[[[155 152 153]
  [155 152 153]
  [152 149 150]
  ...
  [177 179 181]
  [179 179 179]
  [181 181 181]]

 [[155 152 153]
  [155 152 153]
  [153 150 151]
  ...
  [189 191 193]
  [194 194 194]
  [195 195 195]]

 [[154 151 152]
  [154 151 152]
  [153 150 151]
  ...
  [186 188 190]
  [190 190 190]
  [190 190 190]]

 ...

 [[151 151 151]
  [147 147 147]
  [145 145 145]
  ..

[[[155 152 153]
  [158 155 156]
  [155 152 153]
  ...
  [189 188 190]
  [188 188 188]
  [189 189 189]]

 [[156 153 154]
  [158 155 156]
  [156 153 154]
  ...
  [193 192 194]
  [192 192 192]
  [192 192 192]]

 [[155 152 153]
  [158 155 156]
  [155 152 153]
  ...
  [190 189 191]
  [190 190 190]
  [190 190 190]]

 ...

 [[151 148 149]
  [151 148 149]
  [148 145 146]
  ...
  [112 116 118]
  [107 110 110]
  [100 103 103]]

 [[148 145 146]
  [148 145 146]
  [149 146 147]
  ...
  [107 111 113]
  [104 107 107]
  [ 99 102 102]]

 [[144 141 142]
  [146 143 144]
  [149 146 147]
  ...
  [102 106 108]
  [101 104 104]
  [ 98 101 101]]]
the detection is [[[[0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0.

[[[154 151 152]
  [156 153 154]
  [156 153 154]
  ...
  [192 191 193]
  [192 192 192]
  [192 192 192]]

 [[155 152 153]
  [156 153 154]
  [156 153 154]
  ...
  [192 191 193]
  [194 194 194]
  [195 195 195]]

 [[155 152 153]
  [156 153 154]
  [156 153 154]
  ...
  [188 187 189]
  [189 189 189]
  [189 189 189]]

 ...

 [[149 146 147]
  [149 146 147]
  [149 146 147]
  ...
  [109 113 115]
  [107 110 110]
  [101 104 104]]

 [[147 144 145]
  [148 145 146]
  [149 146 147]
  ...
  [106 110 112]
  [105 108 108]
  [101 104 104]]

 [[140 137 138]
  [141 138 139]
  [148 145 146]
  ...
  [104 108 110]
  [101 104 104]
  [ 99 102 102]]]
[[[155 152 153]
  [156 153 154]
  [156 153 154]
  ...
  [193 192 194]
  [193 193 193]
  [193 193 193]]

 [[155 152 153]
  [158 155 156]
  [158 155 156]
  ...
  [190 189 191]
  [193 193 193]
  [194 194 194]]

 [[154 151 152]
  [158 155 156]
  [156 153 154]
  ...
  [187 186 188]
  [189 189 189]
  [189 189 189]]

 ...

 [[149 146 147]
  [149 146 147]
  [149 146 147]
  ..

[[[151 151 151]
  [153 153 153]
  [153 153 153]
  ...
  [189 192 192]
  [192 192 192]
  [193 193 193]]

 [[153 153 153]
  [154 154 154]
  [154 154 154]
  ...
  [187 190 190]
  [189 189 189]
  [192 192 192]]

 [[151 151 151]
  [153 153 153]
  [156 156 156]
  ...
  [186 189 189]
  [189 189 189]
  [189 189 189]]

 ...

 [[147 144 145]
  [148 145 146]
  [149 146 147]
  ...
  [111 114 114]
  [108 111 111]
  [108 111 111]]

 [[141 138 139]
  [145 142 143]
  [147 144 145]
  ...
  [107 110 110]
  [105 108 108]
  [106 109 109]]

 [[139 136 137]
  [141 138 139]
  [145 142 143]
  ...
  [113 116 116]
  [108 111 111]
  [105 108 108]]]
[[[150 150 150]
  [152 152 152]
  [152 152 152]
  ...
  [187 190 190]
  [193 193 193]
  [192 192 192]]

 [[153 153 153]
  [154 154 154]
  [154 154 154]
  ...
  [186 189 189]
  [190 190 190]
  [190 190 190]]

 [[151 151 151]
  [153 153 153]
  [156 156 156]
  ...
  [186 189 189]
  [189 189 189]
  [189 189 189]]

 ...

 [[146 143 144]
  [145 142 143]
  [146 143 144]
  ..

[[[154 154 154]
  [153 153 153]
  [154 154 154]
  ...
  [187 190 190]
  [190 190 190]
  [192 192 192]]

 [[152 152 152]
  [153 153 153]
  [156 156 156]
  ...
  [187 190 190]
  [192 192 192]
  [192 192 192]]

 [[153 153 153]
  [152 152 152]
  [154 154 154]
  ...
  [187 190 190]
  [190 190 190]
  [190 190 190]]

 ...

 [[142 142 142]
  [144 144 144]
  [149 149 149]
  ...
  [112 115 115]
  [107 110 110]
  [104 107 107]]

 [[135 135 135]
  [138 138 138]
  [143 143 143]
  ...
  [111 114 114]
  [105 108 108]
  [101 104 104]]

 [[137 137 137]
  [137 137 137]
  [139 139 139]
  ...
  [116 119 119]
  [109 112 112]
  [104 107 107]]]
[[[152 152 152]
  [152 152 152]
  [156 156 156]
  ...
  [187 190 190]
  [192 192 192]
  [192 192 192]]

 [[151 151 151]
  [152 152 152]
  [156 156 156]
  ...
  [189 192 192]
  [192 192 192]
  [192 192 192]]

 [[153 153 153]
  [153 153 153]
  [156 156 156]
  ...
  [186 189 189]
  [189 189 189]
  [190 190 190]]

 ...

 [[142 142 142]
  [144 144 144]
  [149 149 149]
  ..

[[[152 149 150]
  [151 148 149]
  [153 150 151]
  ...
  [188 188 188]
  [189 189 189]
  [188 188 188]]

 [[152 149 150]
  [152 149 150]
  [154 151 152]
  ...
  [188 188 188]
  [188 188 188]
  [187 187 187]]

 [[154 151 152]
  [154 151 152]
  [156 153 154]
  ...
  [187 187 187]
  [188 188 188]
  [187 187 187]]

 ...

 [[137 134 135]
  [135 132 133]
  [138 135 136]
  ...
  [118 120 122]
  [113 115 117]
  [104 106 108]]

 [[140 137 138]
  [135 132 133]
  [135 132 133]
  ...
  [126 128 130]
  [121 123 125]
  [112 114 116]]

 [[151 148 149]
  [144 141 142]
  [140 137 138]
  ...
  [132 134 136]
  [130 132 134]
  [125 127 129]]]
[[[151 151 151]
  [149 149 149]
  [150 150 150]
  ...
  [188 188 188]
  [189 189 189]
  [188 188 188]]

 [[151 151 151]
  [150 150 150]
  [152 152 152]
  ...
  [188 188 188]
  [188 188 188]
  [187 187 187]]

 [[152 152 152]
  [151 151 151]
  [153 153 153]
  ...
  [187 187 187]
  [188 188 188]
  [187 187 187]]

 ...

 [[137 134 135]
  [135 132 133]
  [138 135 136]
  ..

[[[152 152 152]
  [152 152 152]
  [151 151 151]
  ...
  [185 187 189]
  [188 188 188]
  [189 189 189]]

 [[152 152 152]
  [152 152 152]
  [151 151 151]
  ...
  [184 186 188]
  [188 188 188]
  [187 187 187]]

 [[152 152 152]
  [152 152 152]
  [152 152 152]
  ...
  [183 185 187]
  [185 185 185]
  [183 183 183]]

 ...

 [[143 143 143]
  [138 138 138]
  [132 132 130]
  ...
  [132 132 132]
  [125 127 129]
  [118 120 122]]

 [[150 150 150]
  [144 144 144]
  [138 138 136]
  ...
  [137 137 137]
  [132 134 136]
  [129 131 133]]

 [[149 149 149]
  [147 147 147]
  [140 140 138]
  ...
  [138 138 138]
  [137 139 141]
  [135 137 139]]]
the detection is [[[[0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0.

[[[154 151 152]
  [152 149 150]
  [153 150 151]
  ...
  [189 189 189]
  [188 188 188]
  [188 188 188]]

 [[151 148 149]
  [148 145 146]
  [149 146 147]
  ...
  [189 189 189]
  [188 188 188]
  [188 188 188]]

 [[151 148 149]
  [148 145 146]
  [149 146 147]
  ...
  [188 188 188]
  [187 187 187]
  [187 187 187]]

 ...

 [[136 135 137]
  [136 135 137]
  [135 135 135]
  ...
  [126 128 130]
  [121 123 125]
  [109 111 113]]

 [[142 141 143]
  [137 136 138]
  [136 136 136]
  ...
  [136 135 137]
  [129 131 133]
  [122 124 126]]

 [[146 145 147]
  [143 142 144]
  [138 138 138]
  ...
  [136 135 137]
  [134 136 138]
  [130 132 134]]]
[[[153 150 151]
  [152 149 150]
  [152 149 150]
  ...
  [189 189 189]
  [188 188 188]
  [188 188 188]]

 [[151 148 149]
  [149 146 147]
  [151 148 149]
  ...
  [190 190 190]
  [189 189 189]
  [188 188 188]]

 [[152 149 150]
  [149 146 147]
  [151 148 149]
  ...
  [187 187 187]
  [189 189 189]
  [188 188 188]]

 ...

 [[136 135 137]
  [136 135 137]
  [135 135 135]
  ..

[[[151 151 151]
  [151 151 151]
  [153 150 151]
  ...
  [188 188 188]
  [188 188 188]
  [188 188 188]]

 [[151 151 151]
  [150 150 150]
  [153 150 151]
  ...
  [188 188 188]
  [187 187 187]
  [187 187 187]]

 [[151 151 151]
  [151 151 151]
  [153 150 151]
  ...
  [187 187 187]
  [187 187 187]
  [187 187 187]]

 ...

 [[138 137 139]
  [136 135 137]
  [136 136 136]
  ...
  [119 118 120]
  [111 116 116]
  [104 109 109]]

 [[139 138 140]
  [137 136 138]
  [133 133 133]
  ...
  [129 128 130]
  [119 124 124]
  [112 117 117]]

 [[147 146 148]
  [142 141 143]
  [138 138 138]
  ...
  [138 137 139]
  [132 137 137]
  [128 133 133]]]
[[[149 149 149]
  [149 149 149]
  [151 151 151]
  ...
  [183 186 186]
  [187 187 187]
  [188 188 188]]

 [[149 149 149]
  [149 149 149]
  [151 151 151]
  ...
  [184 187 187]
  [188 188 188]
  [188 188 188]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [186 186 186]
  [188 188 188]
  [187 187 187]]

 ...

 [[138 137 139]
  [136 135 137]
  [137 136 138]
  ..

[[[151 151 151]
  [152 152 152]
  [152 152 152]
  ...
  [184 187 187]
  [189 189 189]
  [190 190 190]]

 [[150 150 150]
  [149 149 149]
  [153 153 153]
  ...
  [184 187 187]
  [189 189 189]
  [189 189 189]]

 [[151 151 151]
  [149 149 149]
  [151 151 151]
  ...
  [186 186 186]
  [188 188 188]
  [187 187 187]]

 ...

 [[137 136 138]
  [136 135 137]
  [135 134 136]
  ...
  [118 120 122]
  [112 115 115]
  [108 111 111]]

 [[143 142 144]
  [139 138 140]
  [137 136 138]
  ...
  [124 128 130]
  [121 124 124]
  [116 119 119]]

 [[146 145 147]
  [144 143 145]
  [140 139 141]
  ...
  [128 132 134]
  [130 133 133]
  [128 131 131]]]
[[[152 152 152]
  [151 151 151]
  [151 151 151]
  ...
  [184 187 187]
  [189 189 189]
  [190 190 190]]

 [[150 150 150]
  [150 150 150]
  [153 153 153]
  ...
  [184 187 187]
  [189 189 189]
  [190 190 190]]

 [[151 151 151]
  [149 149 149]
  [152 152 152]
  ...
  [187 187 187]
  [189 189 189]
  [188 188 188]]

 ...

 [[137 136 138]
  [137 136 138]
  [137 136 138]
  ..

In [7]:
# stop the timer and display FPS information
fps.stop()
print("[INFO] elapsed time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))

# check to see if we need to release the video writer pointer
if writer is not None:
    writer.release()

# if we are not using a video file, stop the camera video stream
if not (input_file!=""):
    vs.release()

# otherwise, release the video file pointer
else:
    vs.release()

# close any open windows
cv2.destroyAllWindows()



[INFO] elapsed time: 49.19
[INFO] approx. FPS: 20.33


In [13]:
import numpy as np
a=np.array([[[1,2,3,4],[2,3,45,5]],[[1,2,3,4],[2,2,2,1]]],np.int32)
a.shape
a[0,1,2]

45

In [16]:
centorid=np.zeros((4,2),dtype="int")

In [19]:
centorid[0]=[4,5]
centorid

array([[4, 5],
       [0, 0],
       [0, 0],
       [0, 0]])

In [20]:
from scipy.spatial import distance as dist
import numpy as np
np.random.seed(42)
objectCentroids = np.random.uniform(size=(2, 2))
print("OC:\n",objectCentroids)
centroids = np.random.uniform(size=(3, 2))
print("C:\n",centroids)
D = dist.cdist(objectCentroids, centroids)
print("D:\n",D)

OC:
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
C:
 [[0.15601864 0.15599452]
 [0.05808361 0.86617615]
 [0.60111501 0.70807258]]
D:
 [[0.82421549 0.32755369 0.33198071]
 [0.72642889 0.72506609 0.17058938]]
